### ISSUE TITLE
Not loading with discord

### ISSUE THREAD

**Issue by therealOri** [bb010g/betterdiscordctl#102]
Just updated to discord 0.0.14 and noticed better discord wasn't launching with discord as it launched.

I typed:
`betterdiscordctl install`
`betterdiscordctl upgrade`
`betterdiscordctl update`

And it still doesn't launch with the new version of discord.
I am also sad that there is no "repair" option with this.

Any help is greatly appreciated!
(I'd also like to have my plugins and stuff still exist)

System notes:
OS: Manjaro Linux (The better Arch)

**Comment by huantianad** [comment]
Also on Manjaro, betterdiscord installed makes discord think it's running on a browser instead of the app, no betterdiscord items show up in settings either

**Comment by True-cc** [comment]
I have this same problem on a fresh Manjaro installation.

**Comment by HerrCraziDev** [comment]
Same issue here as well. `betterdiscordctl status -s /usr/share` gives the following output after being updated, yet BetterDiscord doesn't kicks in once Discord loads.
```
$ betterdiscordctl status -s /usr/share
Discord: /usr/share/discord
Modules: /home/herrcrazi/.config/discord/0.0.14/modules
Index modified: yes
Linked injector directory: /home/herrcrazi/.local/share/betterdiscordctl/bd/0
Linked injector repository: https://github.com/rauenzi/BetterDiscordApp
```

**Comment by frostxyz-bit** [comment]
Having this same issue on Manjaro, with the same weird browser bug @huantianad is describing.

**Comment by therealOri** [comment]
Didn't redirect to the original issue that this is a duplicate of and or help with the issue at all.

Noted*
*very helpful*

**Comment by therealOri** [comment]
You didn't redirect to the original issue that this is a duplicate of and or help with the issue at all.

@ObserverOfTime 
Going off of the BBD Issue label you have provided in the given labels...(next to the Duplicate label)
I don't use canary and I don't use Kali linux. I use stable.
(If that is supposed to be a redirect to the "original". If not then you didn't help worth shit xD)

This entire issue is not resolved and shouldn't be closed. At-least give me/us a link to go to..

**Comment by ObserverOfTime** [comment]
The cause of this and every other new issue is the same as the pinned one.

**Comment by QuantumABI** [comment]
https://github.com/rauenzi/BetterDiscordApp/issues/598#issuecomment-806067616

This part seemed to work for me, in case you still havent found a solution :)

**Comment by therealOri** [comment]
Hey Look!

Someone finally posted a link, to something that may fix my issue.
I am no longer sat here waiting for ANY kind of answer to look into.
It's almost as if they know how to answer someone properly that has an issue.

I'll look into it and thank you @QuantumABI

**Comment by therealOri** [comment]
So far, nothing there has worked @QuantumABI 
Still looking!

**Comment by therealOri** [comment]
@QuantumABI 
I found a patch and it's working now.

https://github.com/rauenzi/BetterDiscordApp/issues/598#issuecomment-807118794
This worked for me.
