### ISSUE TITLE
Betterdiscordctl breaks Discord's new 0.0.14 version of discord.

### ISSUE THREAD

**Issue by WarpWing** [bb010g/betterdiscordctl#104]
Hello! So I upgraded to Discord 0.0.14 by .deb this morning. With that, I uninstalled betterdiscord using betterdiscordctl and then reinstalled it. After that, I no longer was able to right click (which would pop up the menu), Discord didn't recognize any input devices at ALL and it didn't even install BetterDiscord. After running it, Discord 0.0.14 works just fine without BD. 
Discord after attempting to install BetterDiscord
![image](https://user-images.githubusercontent.com/28925758/112375871-29eaee00-8cba-11eb-87bc-285a484de6e8.png)
Commands I ran:
![image](https://user-images.githubusercontent.com/28925758/112375940-3b33fa80-8cba-11eb-8c19-4572b9f35f15.png)
My System Information
![image](https://user-images.githubusercontent.com/28925758/112376052-5ef74080-8cba-11eb-980e-cd3e64375301.png)

**Comment by zany130** [comment]
see here for why and a potential fix https://github.com/rauenzi/BetterDiscordApp/issues/598
