### ISSUE TITLE
Better Discord doesn't work after update

### ISSUE THREAD

**Issue by constantlycurious** [bb010g/betterdiscordctl#106]
Better Discord doesn't work after a update yesterday. I already tried any tips and commands from the issues #53 and #57 but better discord still doesn't work.

I already tried:
`betterdiscordctl install`
`betterdiscord ctl reinstall -v -v`
`betterdiscordctl uninstall` in combination with `betterdiscordctl install`
and `betterdiscordctl update`

I get this weird double horizontal ruler as if something should be there but there are no options:
![4541244](https://user-images.githubusercontent.com/77165433/112401855-5119dd80-8d03-11eb-8cda-c52cf0c55dd9.png)

I also got this error in the console:
![5341240](https://user-images.githubusercontent.com/77165433/112401609-d3ee6880-8d02-11eb-858d-1326605be096.png)

Also nothing in the logs:
![4641243](https://user-images.githubusercontent.com/77165433/112401803-36dfff80-8d03-11eb-9760-0fcf4222104b.png)

Any hints what to do now?

**Thanks in advance!**

**Comment by KaliMasterDev** [comment]
Also discord thinks, that it is browser:
![image](https://user-images.githubusercontent.com/68482946/112433103-14b9a200-8d42-11eb-823f-61971b29fae9.png)

**Comment by iolo53435343** [comment]
Updating discord was the biggest mistake i did.
You should be able to install BD to an older version
Due to me using Linux, i can get the older version.
I don't know about you though.

**Comment by iolo53435343** [comment]
You could try to use a Public Test Build

**Comment by yoge67855** [comment]
i had same problem and i was searching for solution for DAYS and discord PTB work

> You could try to use a Public Test Build.
> 
> EDIT: Discord PTB works.
