### ISSUE TITLE
Trying to load BetterDiscord dosen't work and serves as a Discord web iFrame instead

### ISSUE THREAD

**Issue by oscar2558** [bb010g/betterdiscordctl#109]
After updating the Discord client and betterdiscordctl, I can no longer see BandagedBD settings, and a download button now appears for Discord too.
https://i.imgur.com/JQ2Olsl.png
https://i.imgur.com/LuZ0xve.png

**Comment by oscar2558** [comment]
Also this if that helps
https://i.imgur.com/aIlUw48.png

**Comment by bb010g** [comment]
Duplicate of #96.
