### ISSUE TITLE
Installation changes almost nothing

### ISSUE THREAD

**Issue by Kyrela** [bb010g/betterdiscordctl#110]
### Installation changes almost nothing

**Hello, I'm under Fedora 33 and bdiscordctl doesn't work: it shows me that the installation succeeded, but the only traces of BbetterDiscord that I have are:**

- **a smaller interface** (I'm at 125% normally, against 100% with betterdiscord)

- **This extra separator:**

![Capture d’écran du 2021-03-26 15-39-03](https://user-images.githubusercontent.com/44508673/112648744-19697d80-8e4a-11eb-9705-02e60ea51f44.png)

- **The banner proposing me to install discord**

- **I'm mute and I can't unmute myself**

- **And a different footer:**

Without BD:
![Capture d’écran du 2021-03-26 15-43-13](https://user-images.githubusercontent.com/44508673/112648832-32722e80-8e4a-11eb-88e7-ca2f8c87e7d3.png)
With BD:
![Capture d’écran du 2021-03-26 15-42-42](https://user-images.githubusercontent.com/44508673/112648875-3b630000-8e4a-11eb-96af-4fb702927920.png)

I quickly understood that the only thing that the installation changed was that the web version was "emulated"...

I installed discord via dnf, running the command with sudo just doesn't work.
I tried reinstalling discord via snap, same result. I confess I don't know what to do, not being an expert myself...

Here's my command and its result :
```bash
[Mathis@laptop-de-mathis ~]$ betterdiscordctl install
Cloning https://github.com/rauenzi/BetterDiscordApp...
Clonage dans '/home/Mathis/.local/share/betterdiscordctl/bd/0'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 13 (delta 0), reused 6 (delta 0), pack-reused 0
Réception d'objets: 100% (13/13), 5.55 Kio | 5.55 Mio/s, fait.
Installed. (Restart Discord if necessary.)
```

As you can see, absolutely everything went well.

Any help is welcome!

**Comment by bb010g** [comment]
Duplicate of #96.
