### ISSUE TITLE
betterdiscordctl turns discord into its web version

### ISSUE THREAD

**Issue by Weenut** [bb010g/betterdiscordctl#112]
I'm using the normal version of discord from the official pacman repositories(no canary, snap, flatpak or anything else) and I acquired betterdiscordctl from the aur. When I install betterdiscord instead of actually installing it, it causes discord to behave exactly like the web version(Auto mic sensitivity feature missing, orange notice at the top of the window telling me to download the app). It does however return to normal after uninstalling betterdiscord.

I even tried deleting `~/.config/discord/0.0.14/modules` which worked the last time I had problems with betterdiscordctl

**Comment by TOLHavoc** [comment]
Same issue here. tried flatpak and normal.

**Comment by Weenut** [comment]
This script works flawlessly as long as discord isn't running. This has happened before but then deleting the modules folder fixed the problem.

I'll be sure to try out using the manually downloaded discord(the one that comes as a tar file)

**Comment by Weenut** [comment]
yeah I think I clobbed betterdiscord systemwide because in the output log when running discord(the tar version), says it still uses ~/.config/discord so my only chance is to run discord as root so that it uses /root/.config(which is kinda retarded) or install bd manually without the help of this script

**Comment by bb010g** [comment]
Duplicate of #96.
