### ISSUE TITLE
Discord Installation not found on Pop OS

### ISSUE THREAD

**Issue by Myphz** [bb010g/betterdiscordctl#114]
I've tried installing Better Discord with betterdiscordctl install. It correctly clones the repository without issues, but when I open Discord, nothing has changed. If I try to install another version with betterdiscordctl install -f PTB, I get `ERROR: Discord installation not found. Try specifying it with "--discord".`.

So I tried to specify the path with `betterdiscordctl install -f PTB -s /usr/bin` (My discord executable is /usr/bin/discord), but I still get the same error.
Any fixes?

Thanks in advance!

**Comment by ObserverOfTime** [comment]
What's the output of `betterdiscordctl status`?

**Comment by Myphz** [comment]
```Discord: /usr/share/discord
Modules: /home/daniel/.config/discord/0.0.14/modules
Index modified: no
Linked injector directory: no
Linked injector repository: no
```

**Comment by ObserverOfTime** [comment]
It doesn't look like you've installed PTB then.

**Comment by Myphz** [comment]
No, I didn't. When I try to do that, I get the Discord installation not found error. Right now I've installed the stable version, but nothing has changed on my discord

**Comment by ObserverOfTime** [comment]
You didn't try to install PTB. You tried to install BD on PTB without having installed PTB. That's why it can't be found.
