### ISSUE TITLE
No error message, but no sign of betterdiscord in the settings.

### ISSUE THREAD

**Issue by ModcoLocko** [bb010g/betterdiscordctl#115]
Using flatpack discord on pop os (unbuntu with some minor tweaks) and installed the flatpack package, no sign of better discord tho but no errors while installing.

**Comment by An0nym0us-sh** [comment]
Same here with the snap version in (ubuntu with tweaks) 
One error when upgrading
/usr/local/bin/betterdiscordctl: line 662: syntax error near unexpected token `)'

**Comment by Maritsu** [comment]
Both happened. No sign all the time, changes Discord to a way less stable version of browser version and sometimes I get @An0nym0us-sh's error

**Comment by ObserverOfTime** [comment]
Duplicate of #96 & #97.
