### ISSUE TITLE
discord doesn't change

### ISSUE THREAD

**Issue by booro999** [bb010g/betterdiscordctl#117]
everything looks ok in terminal, but when i open discord nothing changes. i reinstalled both betterdiscordctl and discord. idk what to do. 

![Screenshot from 2021-03-31 19-22-03](https://user-images.githubusercontent.com/81706327/113185167-65eff700-9256-11eb-859c-42241c633660.png)

**Comment by booro999** [comment]
@ObserverOfTime

**Comment by bb010g** [comment]
Duplicate of #96, which will be fixed shortly.
