### ISSUE TITLE
BDctl doesnt work on latest update

### ISSUE THREAD

**Issue by sakutty** [bb010g/betterdiscordctl#118]
When i updated from 0.0.13 to 0.0.14 (i tried these versions none worked after update : deb flatpak and snap) and when installing i get this error(image below) and mic and audio doesnt work and i need to uninstall betterdiscord afterwards the error is gone and audio and mic works again.
![image](https://user-images.githubusercontent.com/69316447/113353180-f78a6200-9345-11eb-9017-1fc81d57c078.png)

**Comment by bb010g** [comment]
Duplicate of #96.
