### ISSUE TITLE
ERROR: Directory 'discord_desktop_core' not found in 

### ISSUE THREAD

**Issue by Pzblo** [bb010g/betterdiscordctl#121]
I tried everything, I reinstalled discord 2 times I really tried everything, I restarted it several times I made these commands in su 
"curl -O https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl"
"chmod +x betterdiscordctl"
"mv betterdiscordctl /usr/local/bin"

and

"betterdiscordctl"

, I restarted several times discord but nothing (im on debian ^^)

WARN: Config directory not found for Discord  (/usr/share/discord, /root/.config/discord).
ERROR: Directory 'discord_desktop_core' not found in

**Comment by ObserverOfTime** [comment]
Use `betterdiscordctl install` without `sudo` but wait until #120 is merged.

**Comment by Pzblo** [comment]
> Use `betterdiscordctl install` without `sudo` but wait until #120 is merged.
haha thank you, I managed to install it , problem after relaunching discord and even restarting my pc and re-installing discord, betterdiscord does not appear? , a solution?

-Thx

**Comment by ObserverOfTime** [comment]
Read the `but` part.

**Comment by Pzblo** [comment]
> Read the `but` part.

what do you mean ? , i'm not very comfortable with github and i don't speak english, why betterdiscord doesn't work?

sorry :x

**Comment by ObserverOfTime** [comment]
See the pinned issue.

**Comment by Pzblo** [comment]
well, i read the subject ten times but i didn't understand anything ?? , why it does not work ??

**Comment by bb010g** [comment]
It doesn't work because of #96, which will be fixed soon.
