### ISSUE TITLE
Discord not beeing detected.

### ISSUE THREAD

**Issue by Brian3647** [bb010g/betterdiscordctl#122]
Hi, I just installed discord from `sudo snap install discord`, bur when I run `ERROR: Discord installation not found. Try specifying it with "--discord".` it does not locate discord. The discord folder installed from snap is in ~/snap, and yes, I tried `betterdiscordctl install -s ~/snap` and says:
```
WARN: Config directory not found for Discord  (/home/victor/snap/discord, /home/victor/.config/discord).
ERROR: Directory 'discord_desktop_core' not found in
```

**Comment by ObserverOfTime** [comment]
You need to use `--snap` but it won't work anyway because of #96.
