### ISSUE TITLE
Nothing happens after installation :(

### ISSUE THREAD

**Issue by TJ2005** [bb010g/betterdiscordctl#123]
I Installed better discord and then launched it there was no bd options in the settings. Help pls
tj@pop-os:~$ curl -O https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19148  100 19148    0     0  49478      0 --:--:-- --:--:-- --:--:-- 49478
tj@pop-os:~$ chmod +x betterdiscordctl
tj@pop-os:~$ sudo mv betterdiscordctl /usr/local/bin
tj@pop-os:~$ 
tj@pop-os:~$ betterdiscordctl install
Cloning https://github.com/rauenzi/BetterDiscordApp...
Cloning into '/home/tj/.local/share/betterdiscordctl/bd/0'...
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 13 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (13/13), 5.53 KiB | 629.00 KiB/s, done.
Installed. (Restart Discord if necessary.)
![image](https://user-images.githubusercontent.com/68985670/114294583-5b86f600-9abd-11eb-94f0-4fd205290733.png)

**Comment by bb010g** [comment]
Duplicate of #96.
