### ISSUE TITLE
Injection failing due to "permission denied, mkdir"

### ISSUE THREAD

**Issue by moreYEE** [bb010g/betterdiscordctl#126]
The betterdiscord installer is working, until apparently there's something wrong with permissions. Is this a problem with my mac, or is it a problem with the software?

The scripts:
Starting Install...

Creating required directories...
✅ Directory exists: /Users/m.li/Library/Application Support/BetterDiscord
✅ Directory exists: /Users/m.li/Library/Application Support/BetterDiscord/data
✅ Directory exists: /Users/m.li/Library/Application Support/BetterDiscord/themes
✅ Directory exists: /Users/m.li/Library/Application Support/BetterDiscord/plugins
✅ Directories created

Downloading asar file
✅ Package downloaded

Injecting shims...
Injecting into: /Applications/Discord.app/Contents/Resources
❌ Could not inject shims to /Applications/Discord.app/Contents/Resources
❌ EACCES: permission denied, mkdir '/Applications/Discord.app/Contents/Resources/app'

The install seems to have failed. If this problem is recurring, join our discord community for support. https://discord.gg/0Tmfo5ZbORCRqbAd

**Comment by ObserverOfTime** [comment]
This issue is for https://github.com/BetterDiscord/Installer

**Comment by Dubcoder** [comment]
im having issues with this too help

**Comment by bb010g** [comment]
@Dubcoder If you have an issue with betterdiscordctl & not BetterDiscord Installer, please create a new issue with more information about your problem.

**Comment by flatypus** [comment]
I found a solution! After a while of debugging, turns out inside the /applications/discord....../Resources/folder, you just need to make a new folder called 'app'. This requires the admin password, which BD doesn't have, but making the folder seemed to let BD install its shims or whatever.

**Comment by jnelken** [comment]
You need to reinstall Discord, as I assume it has the correct/updated folders required for BetterDiscord's install. https://githubmemory.com/repo/BetterDiscord/Installer/issues/164

**Comment by wujingfei1990** [comment]
> 我找到了解决办法！经过一段时间的调试，原来在/applications/discord....../Resources/文件夹中，您只需要创建一个名为“app”的新文件夹。这需要 BD 没有的管理员密码，但制作该文件夹似乎让 BD 安装其垫片或其他任何东西。

解决了，就是新建个app文件夹就可以了

**Comment by BLAMEITONBRADEN** [comment]
A solution I have found is that, in settings go to privacy and security, and go to full disc access. Add better discord to it and it'll work. 
<img width="749" alt="Screenshot 2022-11-16 at 9 38 18 AM" src="https://user-images.githubusercontent.com/64098772/202225065-57bbe0b6-403a-4e65-af9b-f432306a2c4d.png">
