### ISSUE TITLE
Arm version for bettercord

### ISSUE THREAD

**Issue by lololobeb** [bb010g/betterdiscordctl#131]
Please make bettercord available for arm version Linux

**Comment by lololobeb** [comment]
Why it got closed?

**Comment by bb010g** [comment]
betterdiscordctl works fine on AArch32 or AArch64, as long as you can supply the dependencies. betterdiscordctl has no architecture-specific code. If you have problems using betterdiscordctl with an ARM build of Discord's Linux app, please do report those. I don't think BetterDiscord itself does anything architecture-specific.
