### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jacob-02** [bb010g/betterdiscordctl#133]
I am using an Ubuntu 18.04 system. Today on starting up discord, Betterdiscord was not automatically enabled. I re-ran the installation command and it went back to usual. But after a few minutes, the discord crashed again and went back to default. Any help in fixing this issue? If I try to reinstall it, this pops up.
![Screenshot from 2021-07-16 10-29-01](https://user-images.githubusercontent.com/74947682/125894212-b2a9c772-0c16-4290-858c-19cbf819a2d0.png)

**Comment by ObserverOfTime** [comment]
Try `betterdiscordctl -v -v reinstall`

**Comment by jacob-02** [comment]
Tried it
It  reinstalled and still crashed
![Screenshot from 2021-07-20 15-42-27](https://user-images.githubusercontent.com/74947682/126306888-6527d270-2a94-44ef-aafc-3259c5d5d61c.png)

**Comment by ObserverOfTime** [comment]
Have you tried backing up and then removing your plugins?

**Comment by jacob-02** [comment]
This BetterDiscord crashed right on opening Discord. And I don't know how to remove plugins from Discord itself. So any tips in that matter?

**Comment by ObserverOfTime** [comment]
```bash
mv ~/.config/BetterDiscord/plugins{,.bkp}
```

**Comment by jacob-02** [comment]
Ok, it helped. Thanks a lot!

**Comment by ObserverOfTime** [comment]
That means it's not our issue.
