### ISSUE TITLE
Confused between betterdiscordctl, betterdiscord-git and betterdiscord-installer

### ISSUE THREAD

**Issue by PreciousWarrior** [bb010g/betterdiscordctl#134]
There are multiple options for installing BetterDiscord on linux, specifically Arch, since there are 3 AUR packages.

 I would assume `betterdiscord-installer` simply downloads and installs the latest version of the BD installer, and `betterdiscordctl-git` installs betterdiscordctl.

Is there any advantage of using `betterdiscordctl` over `betterdiscord-installer` or vice versa? Does one installer support certain discord versions like Flatpaks, or support injecting into Canary/PTB, etc? Does one installer use a newer injection method that has some problems fixed, like react devtools not loading properly? Is `betterdiscordctl` still maintained now due to there being an official installer for Linux now?

How about directly installing `betterdiscord-git`? This is very convenient because I don't need to go through a two-step process of first installing the installer, and then installing BD. Does it allow you to install on different profiles like Canary / PTB, does it support snap/flatpak? Does it use the `injector` for Linux in the BetterDiscord repo, because that uses an old injection method as has been discussed in various issues regarding manual installation on linux?

Which package would be preferable for BetterDiscord developers, and which would be preferable for a regular user? Do any of these work with `discord_arch_electron`? I feel an answer to these questions would help me as well as many people in the Linux community decide how to install BetterDiscord.

**Comment by ObserverOfTime** [comment]
`betterdiscordctl` is a CLI while `betterdiscord-installer` is a GUI.
Both of them should work with `discord_arch_electron` now.

`betterdiscord-git`has instructions in the pinned comment.
