### ISSUE TITLE
ERROR: Discord modules directory not found.

### ISSUE THREAD

**Issue by ben2611** [bb010g/betterdiscordctl#135]
im trying to install better discord but it doesnt found discord modules 
`betterdiscordctl install`
this is what i tried to install it 
also i tried this but no result 
`betterdiscordctl --flavor PTB install
`

**Comment by ObserverOfTime** [comment]
How did you install Discord.

**Comment by jarjut** [comment]
i also have the same problem
`WARN: Discord  config directory not found (/home/jarjut/.config/discord).`

i install discord with snapstore

**Comment by jarjut** [comment]
i found the config directory in `/home/$user/snap/discord/128/.config/discord`

**Comment by ObserverOfTime** [comment]
> i install discord with snapstore

```
 betterdiscordctl --d-install snap install
 ```
