### ISSUE TITLE
betterdiscordctl cant find discord_desktop_core

### ISSUE THREAD

**Issue by pilot877** [bb010g/betterdiscordctl#137]
I get this error when I try to install better discord
`pilot@localhost:/opt> betterdiscordctl install
ERROR: Directory 'discord_desktop_core' not found in: /home/pilot/.config/discord/0.0.16/modules
`

Any Idea what the problem is? Can't find a solution anywhere

**Comment by ObserverOfTime** [comment]
What's the output of these commands?
```
ls /home/pilot/.config/discord
ls /home/pilot/.config/discord/0.0.16/modules
```

**Comment by ObserverOfTime** [comment]
Start Discord once and try `betterdiscordctl install` again.

**Comment by ObserverOfTime** [comment]
Was it fixed?
