### ISSUE TITLE
betterdiscord doesnt load up for discord-canary when i use it after boot

### ISSUE THREAD

**Issue by ts0ki** [bb010g/betterdiscordctl#139]
this has been happening a lot , im using manjaro linux kde plasma and whenever i open my discord canary after reboot it doesnt open with betterdiscord , discord-ptb and discord vanilla are completely fine 
I reinstalled it and i am getting the same problem

**Comment by ObserverOfTime** [comment]
Canary updates often. You have to use `betterdiscordctl -f canary reinstall` after every update.

**Comment by ts0ki** [comment]
oh okay! thank you so much <3
