### ISSUE TITLE
Invalid update phrase?

### ISSUE THREAD

**Issue by piks** [bb010g/betterdiscordctl#16]
pika@pika-mint ~/bot $ betterdiscordctl upgrade
Downloading betterdiscordctl...
Successfully updated betterdiscordctl.
Local version (1.2.1) is higher than GitHub version (1.4.1).
it updates but is it supposed to say that

**Comment by ObserverOfTime** [comment]
@bb010g I'll leave this one to you, if you don't mind. It might be time to incorporate your semver script.

**Comment by bb010g** [comment]
Oh yeah, I'll take care of that.

**Comment by ObserverOfTime** [comment]
Looks like this was actually a bug with v1.2.1 that has since been fixed.
