### ISSUE TITLE
Discord installation not found on version 0.0.5

### ISSUE THREAD

**Issue by Doomsdayrs** [bb010g/betterdiscordctl#18]
When will there be an update?

**Comment by ObserverOfTime** [comment]
Gonna need more info than that.

**Comment by Doomsdayrs** [comment]
I installed discord from their site, the version was 0.0.5
After login into discord to make sure it was working, i exited out. and went into terminal. 
(I installed betterdiscordctl through the ubuntu installation method you have in the readme) 
When i run the command 
`betterdiscordctl install`
it outputs 
> ERROR : Discord installation not found

**Comment by ObserverOfTime** [comment]
If you're on Ubuntu you should use `betterdiscordctl install -s /usr/share`

**Comment by Doomsdayrs** [comment]
I had to install nodejs-legacy, but after doing so it installed, thanks for the help!

**Comment by Doomsdayrs** [comment]
wait tt

**Comment by Doomsdayrs** [comment]
Isn't there supposed to be a plugins, tbh it seems to just be normal discord

**Comment by Doomsdayrs** [comment]
Nvm, it took a few boots, but its now working
