### ISSUE TITLE
Broken on BD 0.3.0

### ISSUE THREAD

**Issue by clrxbl** [bb010g/betterdiscordctl#19]
With "betterdiscordctl --global-asar -b /usr/lib/betterdiscord-rauenzi-git install" (0.3.0)
![aofryewrgr](https://user-images.githubusercontent.com/28601081/47201387-e7e75080-d379-11e8-88d5-8738ea899b2c.png)

With "betterdiscordctl --global-asar install" (0.3.0)
![cu71r7gu57l](https://user-images.githubusercontent.com/28601081/47201417-064d4c00-d37a-11e8-9bba-9aca93548874.png)

Issue seems to be there for about 2 weeks now but possibly longer.
I already contacted Zerebos / Rauenzi and he told me that this is an issue with betterdiscordctl.

**Comment by ObserverOfTime** [comment]
This is actually an issue with BBD that was [fixed](https://github.com/rauenzi/BetterDiscordApp/commit/32145b8d1ad7acc330a33c727357e7f4ef3553cf) shortly after you posted it.
