### ISSUE TITLE
Not up to date (update betterdiscord)

### ISSUE THREAD

**Issue by RaspberryKitty1** [bb010g/betterdiscordctl#21]
New update of Betterdiscord available 0.3.0.
No bandaged betterdiscord stuff loads

**Comment by ObserverOfTime** [comment]
Use `betterdiscordctl update`.

**Comment by RaspberryKitty1** [comment]
I did it says up to date

**Comment by RaspberryKitty1** [comment]
I did upgrade then update also tried reinstall

**Comment by ObserverOfTime** [comment]
Post the exact commands you ran and their output.

**Comment by RaspberryKitty1** [comment]
OK I can when I get home later today

**Comment by RaspberryKitty1** [comment]
raspberry@Lenovo-ideapad-520-15IKB:~$ betterdiscordctl update  --snap
Updating Git repository...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Total 71 (delta 22), reused 22 (delta 22), pack-reused 48
Unpacking objects: 100% (71/71), done.
From https://github.com/rauenzi/BetterDiscordApp
   16e020d..2f4ef99  stable16   -> origin/stable16
HEAD is now at 2f4ef99 Revert "Revert "allow using hash""

raspberry@Lenovo-ideapad-520-15IKB:~$ betterdiscordctl upgrade
betterdiscordctl is already the latest version (1.4.1).

raspberry@Lenovo-ideapad-520-15IKB:~$ betterdiscordctl reinstall --snap
Killing Discord processes...
Updating asar...
Reinstalled.


![image](https://user-images.githubusercontent.com/28585042/47457135-49595600-d7a4-11e8-9567-a54f5b98d5f6.png)

**Comment by ObserverOfTime** [comment]
Can you post the contents of `~/snap/discord/current/.config/BetterDiscord/logs.log`?

**Comment by RaspberryKitty1** [comment]
``[INF][31/06/2018 03:03:21] Hooking dom-ready
[INF][31/06/2018 03:03:21] Checking data/cache
[INF][31/06/2018 03:03:21] Using repository: rauenzi and branch: master
[INF][31/06/2018 03:03:21] Getting latest hash
[INF][31/06/2018 03:03:22] Downloading Resource: api.github.com/repos/rauenzi/BetterDiscordApp/commits/master
[INF][31/06/2018 03:03:22] Hash: ed66af79180957c79bb495bb87ad443fcd5ace75
[INF][31/06/2018 03:03:22] Getting updater
[INF][31/06/2018 03:03:23] Hooked dom-ready
[INF][31/06/2018 03:03:23] Downloading Resource: raw.githubusercontent.com/rauenzi/BetterDiscordApp/ed66af79180957c79bb495bb87ad443fcd5ace75/data/updater.json
[INF][31/06/2018 03:03:24] Latest Version: 0.2.7
[INF][31/06/2018 03:03:24] Using CDN: cdn.rawgit.com
[INF][31/06/2018 03:03:24] Updating ext data
[INF][31/06/2018 03:03:24] Loading
[INF][31/06/2018 03:03:24] Hooking ipc async
[INF][31/06/2018 03:03:24] Hooked ipc async
[INF][31/06/2018 03:03:24] Loading Resource (jQuery)
[INF][31/06/2018 03:03:24] Loading theme: Twitchcord
[INF][31/06/2018 03:03:24] Loading theme: Custom Badges
[INF][31/06/2018 03:03:24] Loading theme: Custom Labels
[INF][31/06/2018 03:03:24] Loading theme: Twitchcord Fixed
[INF][31/06/2018 03:03:24] Loading theme: Twitchcord badges
[INF][31/06/2018 03:03:24] Loading theme: Twitchcord labels
[INF][31/06/2018 03:03:24] Loading plugin: p_1lib_discord_internals
[INF][31/06/2018 03:03:24] Loading plugin: AccountDetailsPlus
[INF][31/06/2018 03:03:24] Loading plugin: AutoPlayGifs
[INF][31/06/2018 03:03:24] Loading plugin: BetterFormattingRedux
[INF][31/06/2018 03:03:24] Loading plugin: BetterNsfwTag
[INF][31/06/2018 03:03:24] Loading plugin: BetterRoleColors
[INF][31/06/2018 03:03:24] Loading plugin: BlurNSFW
[INF][31/06/2018 03:03:24] Loading plugin: BotsMutualGuilds
[INF][31/06/2018 03:03:24] Loading plugin: ChatFilter
[INF][31/06/2018 03:03:24] Loading plugin: Citador
[INF][31/06/2018 03:03:24] Loading plugin: CompleteTimestamps
[INF][31/06/2018 03:03:24] Loading plugin: CreationDate
[INF][31/06/2018 03:03:24] Loading plugin: detTube
[INF][31/06/2018 03:03:24] Loading plugin: DiscordLogger
[INF][31/06/2018 03:03:24] Loading plugin: FriendNotifications
[INF][31/06/2018 03:03:24] Loading plugin: GoogleTranslateOption
[INF][31/06/2018 03:03:24] Loading plugin: lineNumbers
[INF][31/06/2018 03:03:24] Loading plugin: LinkTooltips
[INF][31/06/2018 03:03:24] Loading plugin: MemberCount
[INF][31/06/2018 03:03:24] Loading plugin: ownerTag
[INF][31/06/2018 03:03:24] Loading plugin: PersonalPins
[INF][31/06/2018 03:03:24] Loading plugin: PinDMs
[INF][31/06/2018 03:03:24] Loading plugin: PinnedMessagesPage
[INF][31/06/2018 03:03:24] Loading plugin: QuickDeleteMessages
[INF][31/06/2018 03:03:24] Loading plugin: ReadAllNotificationsButton
[INF][31/06/2018 03:03:24] Loading plugin: RemoveNicknames
[INF][31/06/2018 03:03:24] Loading plugin: ReverseImageSearch
[INF][31/06/2018 03:03:24] Loading plugin: SendButton
[INF][31/06/2018 03:03:24] Loading plugin: SendEmbeds
[INF][31/06/2018 03:03:24] Loading plugin: ServerFolders
[INF][31/06/2018 03:03:24] Loading plugin: ShowHiddenChannels
[INF][31/06/2018 03:03:24] Loading plugin: ShowImageDetails
[INF][31/06/2018 03:03:24] Loading plugin: SpellCheck
[INF][31/06/2018 03:03:24] Loading plugin: Twitchcord
[INF][31/06/2018 03:03:24] Loading plugin: UserBirthdays
[INF][31/06/2018 03:03:24] Loading plugin: VCMuteSounds
[INF][31/06/2018 03:03:24] Loading plugin: ViewGuildRelationships
[INF][31/06/2018 03:03:24] Loading plugin: afkDeafen
[INF][31/06/2018 03:03:24] Loading plugin: autoSelectServer
[INF][31/06/2018 03:03:24] Loading plugin: betterNSFW
[INF][31/06/2018 03:03:24] Loading plugin: botInfo
[INF][31/06/2018 03:03:24] Loading plugin: charCounter
[INF][31/06/2018 03:03:24] Loading plugin: clearInputOnEsc
[INF][31/06/2018 03:03:24] Loading plugin: dateViewer
[INF][31/06/2018 03:03:24] Loading plugin: dblClickEdit
[INF][31/06/2018 03:03:24] Loading plugin: defaultToEmojis
[INF][31/06/2018 03:03:24] Loading plugin: directDownload
[INF][31/06/2018 03:03:24] Loading plugin: directMedia
[INF][31/06/2018 03:03:24] Loading plugin: discordExperiments
[INF][31/06/2018 03:03:24] Loading plugin: ESorter
[INF][31/06/2018 03:03:24] Loading plugin: evenBetterRepo
[INF][31/06/2018 03:03:24] Loading plugin: forceClose
[INF][31/06/2018 03:03:24] Loading plugin: p_full_offline_list
[INF][31/06/2018 03:03:24] Loading plugin: hexColorPreview
[INF][31/06/2018 03:03:24] Loading plugin: latencyDisplay
[INF][31/06/2018 03:03:24] Loading plugin: Replyer
[INF][31/06/2018 03:03:24] Loading plugin: restartNoMore
[INF][31/06/2018 03:03:24] Loading plugin: searchPlugin
[INF][31/06/2018 03:03:24] Loading plugin: transparency_patcher
[INF][31/06/2018 03:03:24] Loading plugin: unshortenLinks
[INF][31/06/2018 03:03:29] Loading Resource (jQueryCookie)
[INF][31/06/2018 03:03:29] Loading Resource (Main CSS)
[INF][31/06/2018 03:03:29] Loading Resource (Main JS)
[INF][31/06/2018 03:03:30] Starting Up
``
that where the file ends

**Comment by ObserverOfTime** [comment]
That's 3 months out of date for some reason.
Can you check whether the following directories and their contents are owned by your user and not by root?
```
~/snap/discord/current/.config/BetterDiscord
~/snap/discord/current/.config/discord/0.0.5/modules/discord_desktop_core/core/node_modules/betterdiscord
```
Also, `cd` into the latter and run `git rev-parse HEAD`. The output should be `2f4ef9923cb7a6a33c5493c7eb8c5bb64d3df3a5`. If it isn't, something's wrong.

**Comment by RaspberryKitty1** [comment]
Well the .config file is not viewable to me I had to sudo to get into it. And I can try that once I get home from work.

**Comment by RaspberryKitty1** [comment]
And the date on my ubuntu installation could be wrong I have not used it for months. But its the only os I have access to RN due to windows crapping itself

**Comment by RaspberryKitty1** [comment]
Im not home yet but every time i run it with sudo it responds with discord directory not found

**Comment by RaspberryKitty1** [comment]
I got it working appently all i had to do was delete the logs.log file that was not updating

**Comment by RaspberryKitty1** [comment]
Thanks for the help by the way :3

**Comment by RaspberryKitty1** [comment]
hey I am having this issues again but this time not in snap. there is no log file located in /home/.config/betterdiscord that i can share as it wont generate one

i just installed better discord via `betterdiscordctl install -s /usr/share/`

**Comment by RaspberryKitty1** [comment]
when ran from console this is the output
```raspberry@Lenovo-ideapad-520-15IKB:~$ discord
Discord 0.0.9
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/raspberry/.config/discord/0.0.9/modules
[Modules] Module installed file path: /home/raspberry/.config/discord/0.0.9/modules/installed.json
[Modules] Module download path: /home/raspberry/.config/discord/0.0.9/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
[BetterDiscord INF] Hooking dom-ready
[BetterDiscord INF] Checking data/cache
[BetterDiscord INF] Using repository: rauenzi and branch: master
[BetterDiscord INF] Getting latest hash
[BetterDiscord INF] Downloading Resource: api.github.com/repos/rauenzi/BetterDiscordApp/commits/master
[BetterDiscord INF] Hooked dom-ready
[Modules] Starting to install discord_media...
[Modules] Fetching discord_media@0 from https://discordapp.com/api/modules/stable/discord_media/0
[BetterDiscord INF] Hash: 50287f908e68f1a0062c8f1efc2bfb3d9c064bdf
[BetterDiscord INF] Getting updater
[Modules] Streaming discord_media@0 [251 bytes] to /home/raspberry/.config/discord/0.0.9/modules/pending/discord_media-0.zip
[Modules] Finished module downloads. [success: 0] [failure: 1]
[BetterDiscord INF] Downloading Resource: raw.githubusercontent.com/rauenzi/BetterDiscordApp/50287f908e68f1a0062c8f1efc2bfb3d9c064bdf/data/updater.json
[BetterDiscord INF] Latest Version: 0.3.0
[BetterDiscord INF] Using CDN: cdn.rawgit.com
[BetterDiscord INF] Updating ext data
[BetterDiscord INF] Loading
[BetterDiscord INF] Hooking ipc async
[BetterDiscord INF] Hooked ipc async
[BetterDiscord INF] Loading Resource (jQuery)

``` and it ends there

**Comment by RaspberryKitty1** [comment]
i got it to work i del both discord and betterdiscord from the .config folder and reinstalled using `sudo betterdiscordctl install -s /usr/share/` and its working now

**Comment by bb010g** [comment]
…you shouldn't need root to install BetterDiscord? This might cause you issues later. Does not using `sudo` fail for you (if you clear everything out first)?

**Comment by ObserverOfTime** [comment]
The BD log messages show that it works. If it's stuck loading jQuery it's likely a network issue.
