### ISSUE TITLE
betterdiscord not doing  anything 

### ISSUE THREAD

**Issue by Durgefan** [bb010g/betterdiscordctl#23]
so I've installed discord and then I installed betterdiscord-rauenzi-git and that installed just fine. the only issue is it's not affecting discord at all, no matter how times I install or uninstall the two apps it won't kick in. maybe it has to do with the fact when I try to run the command 

"betterdiscordctl install --global-asar -b /usr/lib/betterdiscord-rauenzi-git"

I get the message 

"bash: betterdiscordctl: command not found"

is there something else I need to install?

**Comment by ObserverOfTime** [comment]
Yes. betterdiscordctl.
