### ISSUE TITLE
install function cannot find the install.

### ISSUE THREAD

**Issue by joshuah345** [bb010g/betterdiscordctl#24]
Arch linux
Kernel 4.20 
discord canary latest
no matter how i install it it cant find the installation (also use -f canary)
reinstall option works but status also doesnt

**Comment by ObserverOfTime** [comment]
Please post the full command (with `-v - v` for extra verbosity) and its output.

**Comment by joshuah345** [comment]
sorry for late reply

**Comment by joshuah345** [comment]
typing ``betterdiscordctl status -f canary `` gives me the correct info but using the directory in the install command doesnt help  

Discord: /opt/discord-canary
Modules: /home/joshua/.config/discordcanary/0.0.65/modules
Core patched: no
Index modified: no
Linked core directory: no
Linked core repository: no

**Comment by ObserverOfTime** [comment]
Of course it doesn't. You're supposed its parent (`/opt`) when scanning.

**Comment by joshuah345** [comment]
well before reporting it i tried using /opt and it didnt work either, it should scan it by default (which it already does)

**Comment by ObserverOfTime** [comment]
That's why I said, **post the command and its output**.

**Comment by joshuah345** [comment]
well i tried 
``betterdiscordctl install -f canary``
`` betterdiscordctl install -f canary -d /opt/discordcanary -m /home/joshua/.config/discordcanary/0.0.65/modules``

and it just tells me it cant find it even though status can find it somehow
also tried reinstalling discord and running it again

**Comment by ObserverOfTime** [comment]
The status showed `/opt/discord-canary`. You used `/opt/discordcanary`...
Please run `betterdiscordctl install -f canary -v -v` and *post the output*.

**Comment by joshuah345** [comment]
joshua  ~  betterdiscordctl install -f canary -v -v                   ✘ 1 ``
ERROR: Discord installation not found.``

**Comment by joshuah345** [comment]
ok now i have another issue , i  currently have all 3 versions of discord installed and whenever i do ``betterdiscord install -(any other option)`` it shows the status for stable

**Comment by ObserverOfTime** [comment]
That's weird. Can you try the `next` branch and see if the issue persists? Scanning is currently a bit wonky in master.

**Comment by joshuah345** [comment]
how do i get that (on arch linux)

**Comment by joshuah345** [comment]
same issues, it only shows status even when typing ``betterdiscordctl install -f canary``

**Comment by ObserverOfTime** [comment]
I'm afraid I can't reproduce this issue. Both branches work properly for me.
