### ISSUE TITLE
Doesn't apply after reopening Discord on Arch Linux

### ISSUE THREAD

**Issue by SpaceboyRoss01** [bb010g/betterdiscordctl#25]
Betterdiscordctl had been installed already but when I closed Discord to go home from school, and I reopened it then it didn't start betterdiscord. Already tried the update command, the package is all up to date according to `yay` (yet another yarout).

**Comment by ObserverOfTime** [comment]
Try the `install` command.

**Comment by SpaceboyRoss01** [comment]
Like what I said the install command has already been executed.

**Comment by ObserverOfTime** [comment]
Discord had a versioned update, which changed the directories. You have to run `install` again.

**Comment by SpaceboyRoss01** [comment]
I get `ERROR: Already installed.`

**Comment by ObserverOfTime** [comment]
In that case, run `reinstall`. If Discord updates again afterwards and changes directories, run `install` then .

**Comment by SpaceboyRoss01** [comment]
But this issue was not caused by Discord being updated. It couldn't have been updated because I had no WiFi until I got home and I didn't update the package.

**Comment by ObserverOfTime** [comment]
Just try it for now.

**Comment by SpaceboyRoss01** [comment]
It worked but I feel like there should be a better fix.

**Comment by ObserverOfTime** [comment]
¯\\\_(ツ)_/¯
