### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by EvPayne** [bb010g/betterdiscordctl#28]
~ betterdiscordctl upgrade
/usr/local/bin/betterdiscordctl: line 597: $2=(${major@Q} ${minor@Q} ${patch@Q} ${pre@Q} ${build@Q}): bad substitution
/usr/local/bin/betterdiscordctl: line 597: $2=(${major@Q} ${minor@Q} ${patch@Q} ${pre@Q} ${build@Q}): bad substitution
/usr/local/bin/betterdiscordctl: line 610: x[i]: unbound variable

**Comment by ObserverOfTime** [comment]
What's your bash version?

**Comment by EvPayne** [comment]
~ bash --version
GNU bash, version 4.3.48(1)-release

**Comment by ObserverOfTime** [comment]
Any chance you could upgrade it to 4.4 or newer?

**Comment by EvPayne** [comment]
I was going to compile bash 4.4 myself but the repo is a way better option thanks.
