### ISSUE TITLE
Program cannot find my Discord installation and this time it's not just about /usr/share

### ISSUE THREAD

**Issue by fhuewhd** [bb010g/betterdiscordctl#29]
I've used BetterDiscordCTL before, but this is a new computer and I've had to reinstall Discord and then BetterDiscord.  Well, nothing is working, Discord is just showing up as normal without any sign of BetterDiscord.

I use Ubuntu Xenial Xerus (well, Zorin 12.4 Lite, a variant of it) and am aware of the thing where you have to set the scan directory to /usr/share, and that used to work on the old computer (which ran the equivalent of Trusty, actually, not Xenial, just mentioning that in case it turns out to be relevant), but this time it doesn't work.

Here's what I got out of it on the last round of attempts:

```
user@user-HP-Pavilion-Laptop-15-cw0xxx:~$ betterdiscordctl upgrade
/usr/local/bin/betterdiscordctl: line 597: $2=(${major@Q} ${minor@Q} ${patch@Q} ${pre@Q} ${build@Q}): bad substitution
/usr/local/bin/betterdiscordctl: line 597: $2=(${major@Q} ${minor@Q} ${patch@Q} ${pre@Q} ${build@Q}): bad substitution
/usr/local/bin/betterdiscordctl: line 610: x[i]: unbound variable
user@user-HP-Pavilion-Laptop-15-cw0xxx:~$ betterdiscordctl install
ERROR: Discord installation not found.
user@user-HP-Pavilion-Laptop-15-cw0xxx:~$ betterdiscordctl upgrade -s /usr/share/usr/local/bin/betterdiscordctl: line 597: $2=(${major@Q} ${minor@Q} ${patch@Q} ${pre@Q} ${build@Q}): bad substitution
/usr/local/bin/betterdiscordctl: line 597: $2=(${major@Q} ${minor@Q} ${patch@Q} ${pre@Q} ${build@Q}): bad substitution
/usr/local/bin/betterdiscordctl: line 610: x[i]: unbound variable
user@user-HP-Pavilion-Laptop-15-cw0xxx:~$ betterdiscordctl install -s /usr/share 
Updating asar...
/usr/bin/env: ‘node’: No such file or directory
user@user-HP-Pavilion-Laptop-15-cw0xxx:~$ betterdiscordctl reinstall -s /usr/share
Not installed.
user@user-HP-Pavilion-Laptop-15-cw0xxx:~$ betterdiscordctl update -s /usr/share
Not installed.
```

I assure you Discord IS installed, and it seems to be impying that Node is not installed but I assure you that that is installed too.  I don't know what it is, but I've installed it (both npm and nodejs) repeatedly!

**Comment by ObserverOfTime** [comment]
1. Refer to #28.
2. You need either `nodejs-legacy` or [NodeSource] (/nodesource/distributions)'s package.
