### ISSUE TITLE
invalid option for readarray, line 112 of betterdiscordctl

### ISSUE THREAD

**Issue by piks** [bb010g/betterdiscordctl#3]
pika@Pika-Mint ~/bot/betterDiscord $ betterdiscordctl install -s /usr/share/discord-ptb -f PTB

/usr/local/bin/betterdiscordctl: line 112: readarray: -d: invalid option

readarray: usage: readarray [-n count] [-O origin] [-s count] [-t] [-u fd] [-C callback] [-c quantum] [array]

ERROR: Discord installation not found.

**Comment by piks** [comment]
changing line 112 to `read  -at flavors <<< "$2,"; unset 'flavors[-1]'`
and line 117 to `read -at flavors <<< "${1#*=},"; unset 'flavors[-1]'`
seems to fix

**Comment by bb010g** [comment]
This is happening because Debian is running Bash 4.3, and the `-d` option for `readarray` was introduced in Bash 4.4.

**Comment by piks** [comment]
Yea, couldn't find the man page for the flag the first time through, adding 4.4 found it though, the thing I did was more or less a pass than an implementation. Wasn't sure what -d actually did when I changed because didn't find the page. Wouldn't recommend as a long term fix but I just wanted the script to work 👍

**Comment by bb010g** [comment]
Yeah, I'm looking into a more backwards-compatible fix right now.
