### ISSUE TITLE
betterdiscordctl can't find Flatpak Version

### ISSUE THREAD

**Issue by ProgrammingHider** [bb010g/betterdiscordctl#31]
OS: OpenSuse Tumbleweed
Kernel: 4.20
Discord Install Method: Flatpak

`/home/andreas> betterdiscordctl -V`
`betterdiscordctl 1.5.0`

`/home/andreas> betterdiscordctl install --flatpak -v -v --global-asar`
`VV: Checking`
`Note that the directories`
`'/var/lib/flatpak/exports/share'`
`'/home/andreas/.local/share/flatpak/exports/share'`
`are not in the search path set by the XDG_DATA_DIRS enviroment variable, so`
`applications installed by Flatpak may not appear on your Desktop until the session is restarted.`

`/var/lib/flatpak/app/com.discordapp.Discord/x84_64/stable` 
`/fa97741601c4a3c9cbc55bed8ddb110a79d33e70e40b3327f045889899e68c35/files/extra`
`ERROR: Discord installation not found.`

> https://i.imgur.com/3sCOvhV.png

**Comment by ObserverOfTime** [comment]
Likely related to: https://github.com/bb010g/betterdiscordctl/blob/c98adc60b7cda13545a6e1c6ec858a3377ab3985/betterdiscordctl#L271-L276

You'll have to wait until #30 is fixed and merged, or use another installation method for Discord.

Maybe we should submit an issue to [flatpak](/flatpak/flatpak) asking them to use `stderr` for warnings. :thinking:
