### ISSUE TITLE
Discord installation not found 

### ISSUE THREAD

**Issue by Karozenn** [bb010g/betterdiscordctl#32]
Hi 

CAN you explain step by step what means Point betterdiscordctl to the correct path with the  - - scan  flag. 
I can’t finish to install. 🥺

**Comment by ObserverOfTime** [comment]
> Changes the directories scanned for Discord installations. These are scanned in the order provided. Note that these do not end in `/discord`—if your Discord installation is at `/opt/discord`, then `/opt` should be scanned.

**Comment by Karozenn** [comment]
Thx I am not a geek. I understand what you said but I don't know how. What
are the commands ? Where is discord on my computer ? Can you help me please
?

Le sam. 9 mars 2019 à 14:45, ObserverOfTime <notifications@github.com> a
écrit :

**Comment by ObserverOfTime** [comment]
If you're not a geek why are you using Linux?

How should I know where Discord is on *your* computer?
You haven't even provided any relevant information.

**Comment by Karozenn** [comment]
Ok My question is following : change directives means use command
cd/files/etc ? If yes I understand. If no I won't bore you longer. Thx 😂

Le sam. 9 mars 2019 à 18:37, ObserverOfTime <notifications@github.com> a
écrit :

**Comment by ObserverOfTime** [comment]
I don't quite understand your question. Just tell me which Linux distro you're using.

**Comment by Karozenn** [comment]
Ubuntu 18.04

Le sam. 9 mars 2019 à 19:01, ObserverOfTime <notifications@github.com> a
écrit :

**Comment by ObserverOfTime** [comment]
Then the command you need is
```sh
betterdiscordctl install --scan /usr/share
```

**Comment by Karozenn** [comment]
Thank you so much !

Le sam. 9 mars 2019 à 19:16, ObserverOfTime <notifications@github.com> a
écrit :
