### ISSUE TITLE
No changes in client after successful installation

### ISSUE THREAD

**Issue by SeikatsuChan** [bb010g/betterdiscordctl#35]
Terminal output:
![Selection_001](https://user-images.githubusercontent.com/37958290/56506048-5fde3100-64eb-11e9-9c62-3104bc8ccadf.png)

Discord:
![Selection_002](https://user-images.githubusercontent.com/37958290/56506104-7f755980-64eb-11e9-9e81-70318bfd6639.png)

Running Linux Mint 19.1, Canary build 36132, if that helps at all.

**Comment by ObserverOfTime** [comment]
Use `reinstall`.
