### ISSUE TITLE
Can't upgrade to latest BandagedBD?

### ISSUE THREAD

**Issue by WittyNameHere** [bb010g/betterdiscordctl#38]
The issue:
> An update for BandagedBD is available (0.3.2)! Please Reinstall!

Terminal output:
$ betterdiscordctl update --scan /usr/share/
Updating Git repository...
HEAD is now at 2f4ef99 Revert "Revert "allow using hash""

What I expected:
An updated BandagedBD

What I got:
The same message as before.

**Comment by ObserverOfTime** [comment]
We probably have to switch to the new injection method (#37) in order to update properly.
For now, you can dismiss the modal by pressing the `Okay` button and BBD should continue to work.

**Comment by ObserverOfTime** [comment]
Closing this as it was fixed by rauenzi/BetterDiscordApp#190.

**Comment by ObserverOfTime** [comment]
Here's how to update:
```sh
betterdiscordctl install -v -v -s /usr/share
betterdiscordctl update -v -v
```
If anything goes wrong, please post the output of the commands.
I'll document the update tomorrow.

**Comment by Kastilo** [comment]
Ended up getting this when trying to update
[kastilo@RED-OS-PA ~]$ betterdiscordctl update -v -v -s /opt
VV: Scanning /opt
VV: Trying flavor ''
V: Using Discord at /opt/discord
V: Found modules in /home/kastilo/.config/discord/0.0.9/modules
Updating Git repository...
fatal: ambiguous argument 'origin/injector': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
when installing it claims to have installed but doesn't show up at all

**Comment by JeremyStepp** [comment]
I am using flatpak and the update finishes with no errors, but all that shows up in discord is the icon in the bottom right. The status command shows it as indexed, but nothing else, and I have tried restarting. Here is the output of the commands:

betterdiscordctl --flatpak install -v -v
```
VV: Checking /var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378/files/extra
V: Using Discord at /var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378/files/extra
V: Found modules in /home/jeremy/.var/app/com.discordapp.Discord/config/discord/0.0.9/modules
V: Injecting into index.js...
V: Copying BetterDiscord injector...
Installed. (Restart Discord if necessary.)

```

betterdiscordctl --flatpak update -v -v

```
VV: Checking /var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378/files/extra
V: Using Discord at /var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378/files/extra
V: Found modules in /home/jeremy/.var/app/com.discordapp.Discord/config/discord/0.0.9/modules
Updating Git repository...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (56/56), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 54 (delta 25), reused 49 (delta 21), pack-reused 0
Unpacking objects: 100% (54/54), done.
From https://github.com/rauenzi/BetterDiscordApp
 * branch            injector   -> FETCH_HEAD
HEAD is now at 1c2e6f6 update for linux
```

**Comment by ObserverOfTime** [comment]
Since BD shows the icon, it means `betterdiscordctl` has done its job. You should check the Discord console for errors and submit an issue at [rauenzi/BetterDiscordApp](https://github.com/rauenzi/BetterDiscordApp/issues) or ask for help in the support server. If it turns out to be related to `betterdiscordctl` after all, then submit a new issue here. @JeremyStepp

**Comment by S-B99** [comment]
```bash
usr@ubuntuhost:~/Downloads/bdinstaller$ betterdiscordctl install -v -v
VV: Scanning /opt
VV: Trying flavor ''
VV: Trying flavor 'canary'
VV: Trying flavor 'ptb'
VV: Scanning /usr/share
VV: Trying flavor ''
V: Using Discord at /usr/share/discord
V: Found modules in /home/usr/.config/discord/0.0.9/modules
ERROR: Already installed.
usr@ubuntuhost:~/Downloads/bdinstaller$ betterdiscordctl update -v -v
VV: Scanning /opt
VV: Trying flavor ''
VV: Trying flavor 'canary'
VV: Trying flavor 'ptb'
VV: Scanning /usr/share
VV: Trying flavor ''
V: Using Discord at /usr/share/discord
V: Found modules in /home/usr/.config/discord/0.0.9/modules
Updating Git repository...
From ssh://github.com/rauenzi/BetterDiscordApp
 * branch            injector   -> FETCH_HEAD
HEAD is now at 1c2e6f6 update for linux
```
I still don't have a config area, nor are my plugins being loaded

**Comment by ObserverOfTime** [comment]
Do you see the flashing BD icon at the bottom right? If so, refer to my [previous comment](#issuecomment-497418164).
