### ISSUE TITLE
fatalambiguous argument 'origin/injector': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by piks** [bb010g/betterdiscordctl#39]
```
pika@pika-mint ~/.local/share/betterdiscordctl/bd/0 $ betterdiscordctl update -f PTB -s /usr/share
Updating Git repository...
fatal: ambiguous argument 'origin/injector': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by piks** [comment]
I know it's something to do with git not finding the proper branch/repo but I don't know what it expects

**Comment by ObserverOfTime** [comment]
I cannot reproduce this. What's your git version?
Does this patch fix it?
```patch
diff --git i/betterdiscordctl w/betterdiscordctl
index c6b8bfa..5ee58c7 100755
--- i/betterdiscordctl
+++ w/betterdiscordctl
@@ -383,7 +383,7 @@ bdc_update() {
   if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
     printf 'Updating Git repository...\n' >&2
     git fetch origin
-    git reset --hard "origin/$bd_repo_branch"
+    git reset --hard "origin/$bd_repo_branch" --
   else
     printf 'WARN: No Git repository found.\n' >&2
   fi
```

**Comment by piks** [comment]
```
pika@pika-mint ~/.local/share/betterdiscordctl/bd/0 $ git --version
git version 2.17.1
pika@pika-mint ~/.local/share/betterdiscordctl/bd/0 $ betterdiscordctl update -f PTB -s /usr/share
Updating Git repository...
fatal: Failed to resolve 'origin/injector' as a valid revision.
pika@pika-mint ~/.local/share/betterdiscordctl/bd/0 $ 
```

**Comment by piks** [comment]
I've attempted to go to the injector and try the command manually, still no luck, does that branch exist still? I know they did an update yesterday to BD

**Comment by piks** [comment]
I don't know how it happend but something screwed my git repo, I moved the /usr/share/betterdiscordctl repo and just reinstalled and the issue went away, no idea what caused it but it resolved.

**Comment by ObserverOfTime** [comment]
You mean `~/.local/share/betterdiscordctl`, right?

**Comment by piks** [comment]
Yea I mean't that

**Comment by yumenetwork** [comment]
I'm getting the same error on the update command : 
`betterdiscordctl update -v -v                                                              
VV: Scanning /opt
VV: Trying flavor ''
VV: Trying flavor 'canary'
VV: Trying flavor 'ptb'
VV: Scanning /usr/share
VV: Trying flavor ''
V: Using Discord at /usr/share/discord
V: Found modules in /home/yume/.config/discord/0.0.9/modules
Updating Git repository...
fatal: argument 'origin/injector' ambigu : révision inconnue ou chemin inexistant.
Utilisez '--' pour séparer les chemins des révisions, comme ceci :
'git <commande> [<révision>...] -- [<chemin>...]'`

The install command works well but doesn't change anything in discord. BetterDiscord doesn't start.
However it was working before the latest update of BD... Maybe you can reopen the issue ?

**Comment by ObserverOfTime** [comment]
Try redownloading the latest version (not via `upgrade`).
