### ISSUE TITLE
[Bug] git@github.com: Permission denied (publickey). 

### ISSUE THREAD

**Issue by S-B99** [bb010g/betterdiscordctl#41]
**Describe the Bug**
The public key is denied when trying to clone betterdiscord

**To Reproduce**

1. curl -O https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl
2. chmod +x betterdiscordctl
3. sudo mv betterdiscordctl /usr/local/bin
4. sudo betterdiscordctl install

**Expected Behavior**
It allows me to clone

**Discord Version**
Stable 

**Additional Context**
See for the parent issue https://github.com/rauenzi/BetterDiscordApp/issues/201

**Comment by ObserverOfTime** [comment]
**Do not use `sudo` with `betterdiscordctl` commands (sans `upgrade`).**

P.S. See https://help.github.com/en/articles/error-permission-denied-publickey
