### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by S-B99** [bb010g/betterdiscordctl#42]
To reproduce

1. Install Discord
2. Install BetterDiscord
3. Launch Discord
![image](https://user-images.githubusercontent.com/17222512/58763229-2951f800-8526-11e9-806a-5f8ce6144b60.png)
I did not use sudo as per #41 

Running `betterdiscordctl reinstall` gives `/usr/local/bin/betterdiscordctl: line 502: /home/usr/.local/share/betterdiscordctl/bd_map: Permission denied`

**Comment by ObserverOfTime** [comment]
You have to remove `/home/usr/.local/share/betterdiscordctl` since it was created with `sudo` and try again.

**Comment by S-B99** [comment]
Reinstalled, got 
```bash
usr@ubuntuhost:~/Downloads/bdinstaller$ betterdiscordctl install
Cloning https://github.com/rauenzi/BetterDiscordApp...
Cloning into '/home/usr/.local/share/betterdiscordctl/bd/0'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (12/12), 6.39 KiB | 6.39 MiB/s, done.
Installed. (Restart Discord if necessary.)
```
I don't see BetterDiscord options anywhere (restarted discord as well.)
Also tried `betterdiscordctl reinstall`
![image](https://user-images.githubusercontent.com/17222512/58763913-1132a680-852f-11e9-82d7-b9a0c65ed33e.png)

**Comment by ObserverOfTime** [comment]
See [#38](https://github.com/bb010g/betterdiscordctl/issues/38#issuecomment-497049666)
