### ISSUE TITLE
flatpak error

### ISSUE THREAD

**Issue by ledudulela** [bb010g/betterdiscordctl#45]
First, sorry for my english :)
When i try to execute the command: /betterdiscordctl install --flatpak
I've got an error: "ERROR: Discord installation not found."
So, I added comments on the following rows:
#  flatpak_location=$("$flatpak_bin" info --show-location com.discordapp.Discord)
#  flatpak_location=${flatpak_location##*$'\n'}
#  discord=${flatpak_location:?}/files/extra
and add this one to set discord variable with the real folder:
discord='/var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378/files/extra/'

The command "./betterdiscordctl install --flatpak" is now ok.
So, I think there is a problem with the row:  flatpak_location=$("$flatpak_bin" info --show-location com.discordapp.Discord) and the option "info" of flatpak.

Thank You

**Comment by ObserverOfTime** [comment]
What's the output of `flatpak info --show-location com.discordapp.Discord`?

**Comment by ledudulela** [comment]
flatpak info --show-location com.discordapp.Discord
error: Unknown option --show-location

flatpak --version
Flatpak 0.8.9

OS: Linux Mint Debian Edition 3
uname -a
Linux pc1 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux

**Comment by ObserverOfTime** [comment]
Can you update flatpak? It seems that `--show-location` was introduced in [v1.0.0](https://github.com/flatpak/flatpak/releases/tag/1.0.0).

**Comment by ledudulela** [comment]
No i can't . Flatpak installation depends on update system of LMDE .
So it's not a problem of your script but a version problem of flatpak.
In this case, you could obtain the directory of Discord with the command:

`flatpak info com.discordapp.Discord` 
The return of this command is:
**app/com.discordapp.Discord/x86_64/stable** flathub **8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378**

If you replace " flathub " (wtith space befor and after) in this previous string by the last string you can build the installation directory: 
discord='/var/lib/flatpak/**app/com.discordapp.Discord/x86_64/stable**/**8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378**/files/extra/'

It's just an idea :)

**Comment by ObserverOfTime** [comment]
I can't find a way to reliably get the location since `v0.8.9` doesn't show whether it was installed system-wide or per-user. Moreover, the output of `flatpak info` is way too inconsistent between versions:

**v1.4.0**
```sh
$ flatpak info com.discordapp.Discord

Discord - Chat client

          ID: com.discordapp.Discord
         Ref: app/com.discordapp.Discord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.0.9
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 3.0 MB
     Runtime: org.freedesktop.Platform/x86_64/18.08
         Sdk: org.freedesktop.Sdk/x86_64/18.08

      Commit: 8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378
      Parent: 0b2fdc203d5e26872dcec04ed18fa87edfc3c548ae57518a89baa2e1f39ff46d
     Subject: Use xdg-run/app/$id dir instead of custom one (f9017362)
        Date: 2019-05-29 01:22:17 +0000
$ flatpak info --show-location com.discordapp.Discord
/var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378
```

**v1.0.7**

```sh
$ flatpak info com.discordapp.Discord
Ref: app/com.discordapp.Discord/x86_64/stable
ID: com.discordapp.Discord
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2019-05-29 01:22:17 +0000
Subject: Use xdg-run/app/$id dir instead of custom one (f9017362)
Commit: 8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378
Parent: 0b2fdc203d5e26872dcec04ed18fa87edfc3c548ae57518a89baa2e1f39ff46d
Location: /var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378
Installed size: 3.0 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08
$ flatpak info com.discordapp.Discord | sed -n 's/Location: //p'
/var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378
```

**v0.8.9**
```sh
$ flatpak info com.discordapp.Discord
app/com.discordapp.Discord/x86_64/stable flathub 8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378
$ flatpak info com.discordapp.Discord | sed 's| flathub |/|'
app/com.discordapp.Discord/x86_64/stable/8a0fc700c701feacfc3e8cc630fbcbd7ff98c13045cfdf5cbc1aea6e7b307378
$ # ^ closest I can get to the full path
```

**Comment by ObserverOfTime** [comment]
What I'm gonna do instead is make it so the `-d, --discord` & `-m, --modules` options can be used with `--flatpak` to manually specify the location:

```sh
betterdiscordctl $bdctl_command --flatpak \
  -d /var/lib/flatpak/app/com.discordapp.Discord/current/active/files/extra \
  -m ~/.var/app/com.discordapp.Discord/config/discord/$discord_version/modules
```
* Replace `$bdctl_command` with whatever command you need (e.g. `install`).
* Replace `$discord_version` with the current Discord version (e.g. `0.0.9`).
* If Discord was installed with `--user` then `/var/lib/` should be `~/.local/share/`.

**Comment by ledudulela** [comment]
Ok, you could suggest this options when  "ERROR: Discord installation not found" message appear.
Anyway, thank you ++

**Comment by ryaniskira** [comment]
@ObserverOfTime This does not work.

```
betterdiscordctl install --flatpak \
-d /var/lib/flatpak/app/com.discordapp.Discord/current/active/files/extra \
-m ~/.var/app/com.discordapp.Discord/config/discord/0.0.9/modules
```

Simply produces:
```
ERROR: Discord installation not found.
```

This is installed as system not user and in fact the "extra" folder doesn't even exist. The only folders that exist are bin, discord, lib, and share.

**Comment by ryaniskira** [comment]
@ObserverOfTime Nice workaround, but do note for some reason the "extra" folder did not exist for me and I had to manually create it.

**Comment by ObserverOfTime** [comment]
@ryaniskira What version of flatpak are you using?

**Comment by ryaniskira** [comment]
@ObserverOfTime 

> /var/lib/flatpak/app/com.discordapp.Discord/current/active/files/discord

I actually tried that first and it didn't work, manually creating the extra folder then pointing to that did work.

**Comment by ledudulela** [comment]
It works for me.
Comments following lines (from 425 to 436):
<pre>
  flatpak_version=$("$flatpak_bin" --version | sed -n 's/Flatpak //p')
  if [[ $(Semver::compare "$flatpak_version" '1.0.0') -eq -1 ]]; then
    die 'ERROR: You are using an unsupported version of Flatpak.' \
        'See https://github.com/bb010g/betterdiscordctl/issues/45'
  fi
  # flatpak sucks and doesn't use stderr for warnings.
  # https://github.com/flatpak/flatpak/blob/13e449b/app/flatpak-main.c#L259-L286
  # This really should be better for directories with newlines, but...
  # We're just going to grab the last line and hope for the best.
  flatpak_location=$("$flatpak_bin" info --show-location com.discordapp.Discord)
  flatpak_location=${flatpak_location##*$'\n'}
  discord=${flatpak_location:?}/files/extra
</pre>
and add
<pre>
  discord='/var/lib/flatpak/app/com.discordapp.Discord/current/active/files/discord/'
</pre>

**Comment by ObserverOfTime** [comment]
You can achieve the same thing by using `-d '/var/lib/flatpak/app/com.discordapp.Discord/current/active/files/discord/'`.
