### ISSUE TITLE
Add release

### ISSUE THREAD

**Issue by FFY00** [bb010g/betterdiscordctl#46]
I am about to move discord, betterdiscord and betterdiscordctl the Archlinux repos. Could you please add a release?

---

Edited to keep track of what's been packaged:

- [x] Discord
- [ ] Discord PTB
- [ ] Discord Canary
- [ ] ~~betterdiscordctl~~
- [ ] ~~Bandaged BD~~

**Comment by ObserverOfTime** [comment]
@bb010g

**Comment by FFY00** [comment]
I just noticed you guys are the ones maintaining the AUR packages. Discord gave us permission to distribute their client so I am moving it to the official repos. I would also like to do the same with betterdiscord/betterdiscordctl.

**Comment by bb010g** [comment]
Thanks for offering to formally package betterdiscordctl! I'll try to get a release out today, along with an actual manpage to make this friendlier to use. Could you clarify how you're planning to package `betterdiscord`? Straight upstream of current `betterdiscord-rauenzi-git` (sans VCS)?

**Comment by FFY00** [comment]
I am going package the tags, if the latest tag is not working for the latest discord I will ask for a new release there. If this models proves to not work well I will just checkout a working commit.

**Comment by ObserverOfTime** [comment]
The tags are for the Windows & Mac installers. You should checkout a commit from the `injector` branch and use this for the `pkgver`: https://github.com/rauenzi/BetterDiscordApp/blob/injector/betterdiscord/config.json#L8. Then, update the package whenever that version changes.

**Comment by ObserverOfTime** [comment]
@FFY00 I noticed that [betterdiscordctl](https://www.archlinux.org/packages/community/x86_64/betterdiscordctl/) was removed from the community repo not so long after you added it. What happened?

**Comment by FFY00** [comment]
Basically people on the team complained about it. They said it was breaking the Discord ToS. Sorry about that.

**Comment by ObserverOfTime** [comment]
Makes sense. Are you gonna package the other Discord flavors?

**Comment by FFY00** [comment]
I did package them but the team was against it, so they were removed.

**Comment by ObserverOfTime** [comment]
That's a shame. I use PTB myself. Should we close this issue now?

**Comment by FFY00** [comment]
I do have proper PKGBUILDs, if you want you can maintain it in the AUR or create a custom Arch repo. If you just keep the PKGBUILD in sync with the one I maintain in the `discord` package you shouldn't have any trouble. Even if you do you can just let me know :smile:.

**Comment by ObserverOfTime** [comment]
I'll just stick to the AUR package for now, thanks.
