### ISSUE TITLE
BetterDiscord's gone again.

### ISSUE THREAD

**Issue by fhuewhd** [bb010g/betterdiscordctl#47]
After a Discord update (though that's not saying much, there seems to be a Discord update of some sort almost every day as far as I can tell), BetterDiscord has disappeared - all my customisations are gone and BetterDiscord doesn't appear on the settings page.  

Tried uninstalling and reinstalling using BetterDiscordCTL (using the various instructions I've had in answer to previous "Issues" I've started - note that it still appears to be necessary to install an outdated version of "asar" to get BetterDiscordCTL to work).  It said BetterDiscord had installed successfully, but when I restarted Discord there was still no sign of BetterDiscord.

Any idea how to fix this, please?  Is anyone else having a problem?

**Comment by ObserverOfTime** [comment]
#38

**Comment by fhuewhd** [comment]
Shortest ever (working) answer  :-)  That's got it.  Thanks very much, that was quick.  I had had a quick look at the list of existing issues but didn't recognise that that had anything to do with it.  (Should have, I HAVE been seeing the instantly-vanishing-Please-Update-message for some time, now I think about it.  I've been tired lately and hence gormless.)
