### ISSUE TITLE
fatal javascript error ubuntu 

### ISSUE THREAD

**Issue by sKirua** [bb010g/betterdiscordctl#48]
![image](https://user-images.githubusercontent.com/43117514/60682992-cee5e780-9e95-11e9-82e4-d593ecc16c5c.png)

**Comment by ObserverOfTime** [comment]
What are the commands you ran and what is their output?

**Comment by sKirua** [comment]
idk the output of this command but this is the last command i launched bcs betterdiscord doesn't installed 

  956  betterdiscordctl install --global-asar -b /usr/lib/BetterDiscordApp/ -v -v

**Comment by ObserverOfTime** [comment]
Did you actually install BBD in `/usr/lib/BetterDiscordApp/`?
This is the command you need to run if you didn't:
```betterdiscordctl reinstall -v -v```

**Comment by sKirua** [comment]
it doesn't works 
![image](https://user-images.githubusercontent.com/43117514/60683964-42d6be80-9e9b-11e9-8b5d-c05e0d2ccd3b.png)

**Comment by sKirua** [comment]
i think i did

**Comment by ObserverOfTime** [comment]
Run these and post the output.
```
ls /usr/lib/BetterDiscordApp/
betterdiscordctl install -v -v
betterdiscordctl install -b /usr/lib/BetterDiscordApp/ -v -v
```

**Comment by sKirua** [comment]
ls /usr/lib/BetterDiscordApp/
ls: cannot access '/usr/lib/BetterDiscordApp/': No such file or directory

**Comment by sKirua** [comment]
![image](https://user-images.githubusercontent.com/43117514/60684130-33a44080-9e9c-11e9-9188-831ad7b2fb02.png)
![image](https://user-images.githubusercontent.com/43117514/60684138-40289900-9e9c-11e9-8698-313d9a1388ad.png)

**Comment by ObserverOfTime** [comment]
```
rm -f ~/.config/discord/0.0.9/modules/discord_desktop_core/injector
betterdiscordctl install -v -v
```
This should fix it.

**Comment by sKirua** [comment]
Now i can launch discord but betterdiscord is not installed
![image](https://user-images.githubusercontent.com/43117514/60684221-aad9d480-9e9c-11e9-9b4e-39566a61f5a6.png)

**Comment by sKirua** [comment]
output: 

![image](https://user-images.githubusercontent.com/43117514/60684241-c47b1c00-9e9c-11e9-841c-98bcbaca522f.png)

**Comment by ObserverOfTime** [comment]
No BD icon on the bottom right? Have you checked the settings?

**Comment by sKirua** [comment]
yes 
![image](https://user-images.githubusercontent.com/43117514/60684311-479c7200-9e9d-11e9-9938-abf24e3b0f16.png)

**Comment by ObserverOfTime** [comment]
Check the Discord console with `Ctrl` + `Shift` + `I` and screenshot any errors your see.

**Comment by sKirua** [comment]
![image](https://user-images.githubusercontent.com/43117514/60684419-f2149500-9e9d-11e9-8e7f-b7f948130c18.png)

**Comment by ObserverOfTime** [comment]
Did you have Discord open when you ran `install`? Try quitting and restarting it.

**Comment by sKirua** [comment]
it doesn't work

**Comment by ObserverOfTime** [comment]
What doesn't work? Did you quit it with `Ctrl` + `Q`?

**Comment by sKirua** [comment]
i killed the process

**Comment by sKirua** [comment]
i tried with ctrl + Q but doesn't work

**Comment by ObserverOfTime** [comment]
This is weird. What's the output of `betterdiscordctl status -v -v`?

**Comment by sKirua** [comment]
![image](https://user-images.githubusercontent.com/43117514/60684597-0016e580-9e9f-11e9-991b-4f17770df880.png)

**Comment by ObserverOfTime** [comment]
Try `betterdiscordctl reinstall -v -v`. If it doesn't work, log out and see what happens when you log in again (https://github.com/rauenzi/BetterDiscordApp/issues/202#issuecomment-498090283).

**Comment by sKirua** [comment]
nothing happend  but this is the output :
![image](https://user-images.githubusercontent.com/43117514/60684741-c0043280-9e9f-11e9-9b80-a5f51dbaf36a.png)

**Comment by ObserverOfTime** [comment]
Did you log out?

**Comment by sKirua** [comment]
yes nothing

**Comment by ObserverOfTime** [comment]
What's the output of
```
cat ~/.config/discord/0.0.9/modules/discord_desktop_core/index.js
git -C ~/.config/discord/0.0.9/modules/discord_desktop_core/injector log -1
```

**Comment by sKirua** [comment]
![image](https://user-images.githubusercontent.com/43117514/60685067-73215b80-9ea1-11e9-9a55-42458d3d5760.png)

**Comment by ObserverOfTime** [comment]
All right, I thought this wouldn't be needed but turns out I was wrong.
`betterdiscordctl update -v -v` will fix it for real this time.

**Comment by sKirua** [comment]
![image](https://user-images.githubusercontent.com/43117514/60685160-dad7a680-9ea1-11e9-8fdc-58700fb4636e.png)

**Comment by ObserverOfTime** [comment]
Restart Discord.

**Comment by sKirua** [comment]
Thank you it's fixed m8
