### ISSUE TITLE
Missing module: Arch Linux

### ISSUE THREAD

**Issue by gdude2002** [bb010g/betterdiscordctl#49]
An issue I'm sure you guys are familiar with by now. I did have a look around the issues already present in the repo, but nothing has worked so far.

![image](https://user-images.githubusercontent.com/204153/62609381-90f73b80-b8f9-11e9-8567-638f398ad4e1.png)

Discord just made it into Arch's community repo (it was in the AUR before that), so a version update might have broken things.

**Discord**: `0.0.9-4`
**betterdiscordctl**: `1.6.1-1`

**Comment by MEXdave1997** [comment]
Having the same issue rn. The only thing that lets me launch discord is just to uninstall betterdiscord for now. Hopefully this is patched at some point.

**Comment by bioflugel** [comment]
I have same error how fix it ?

**Comment by bb010g** [comment]
Unless @ObserverOfTime can get to this sooner, I'll have to set up an Arch VM to test this, so it may be a bit unless someone else can give some better debugging info.

**Comment by ObserverOfTime** [comment]
My laptop is currently out of commission so I can't verify this issue but it should be fixed by rauenzi/BetterDiscordApp@1434e53. Running the `update` command should do it.

**Comment by ObserverOfTime** [comment]
Seems to be working on Arch with the latest packages.
