### ISSUE TITLE
betterdiscord wont install

### ISSUE THREAD

**Issue by orblazer** [bb010g/betterdiscordctl#50]
Hello,

I want install better discord but this tool doesn't make error and when i run discord the better discord is not loaded (probably not installed).

The output of `betterdiscordctl -v` :
```
V: Using Discord at /opt/discord
V: Found modules in /home/orblazer/.config/discord/0.0.9/modules
Discord: /opt/discord
Modules: /home/orblazer/.config/discord/0.0.9/modules
Index modified: yes
Linked injector directory: /home/orblazer/.local/share/betterdiscordctl/bd/0
Linked injector repository: https://github.com/rauenzi/BetterDiscordApp
```

Thanks for your help.

**Comment by lugia19** [comment]
Same exact issue here as well.

**Comment by ObserverOfTime** [comment]
I can't reproduce this issue.
Are you using the latest version of betterdiscordctl?
What is your distro?
Can you post the full install command and its output?

**Comment by orblazer** [comment]
I am on Antergos (5.29-arch1-1-ARCH).

The version of betterdiscordctl (installed from the package manager, https://aur.archlinux.org/packages/betterdiscordctl-git): 1.6.1
The install command :
```
> betterdiscordctl install -v
V: Using Discord at /opt/discord
V: Found modules in /home/orblazer/.config/discord/0.0.9/modules
V: Injecting into index.js...
V: Linking BetterDiscord injector...
Installed. (Restart Discord if necessary.)
```

**Comment by ObserverOfTime** [comment]
Open the Discord console with `Ctrl` + `Shift` + `I` and screenshot any errors.

**Comment by orblazer** [comment]
I don't have any error, i think is just not installed 

![Screenshot_20190825_111411](https://user-images.githubusercontent.com/1344792/63647998-7dd1d180-c729-11e9-8c5c-87c5cba8b339.png)

**Comment by lugia19** [comment]
I'm on Kali (2019.2, based on debian testing)
Betterdiscordctl's version is 1.6.1

The install command:
`betterdiscordctl install -v
V: Using Discord at /usr/share/discord
V: Found modules in /home/admin/.config/discord/0.0.9/modules
V: Injecting into index.js...
V: Linking BetterDiscord injector...
Installed. (Restart Discord if necessary.)
`

![Screenshot from 2019-08-25 11-26-55](https://user-images.githubusercontent.com/21088033/63648118-524fe680-c72b-11e9-8fc0-79cd425f401f.png)

**Comment by ObserverOfTime** [comment]
I don't know what could be causing this. @bb010g any ideas?

**Comment by ObserverOfTime** [comment]
Did you perhaps try to install another mod like PowerCord/EnhancedDiscord? They don't play well with BetterDiscord.

**Comment by orblazer** [comment]
No i have clean discord (i have try remove all discord and betterdiscord on my computer, and reinstall them)

**Comment by lugia19** [comment]
Completely clean install here as well, never installed any other mod.

**Comment by lugia19** [comment]
Uninstalled betterdiscord and discord, redownloaded betterdiscordctl and reinstalled everything, still not working.

**Comment by Samega7Cattac** [comment]
Same issue here: Arch (5.2.13-arch1-1-ARCH)
I solved it by using the manual method and moving the `betterdiscordctl` to `/usr/bin/` instead on `/usr/local/bin/`, since it would give this error: `bash: /usr/bin/betterdiscordctl: No such file or directory`.

**Comment by ObserverOfTime** [comment]
`betterdiscordctl-git` uses the exact same executable as the manual installation method. It just disables the self-upgrade. I don't see how this fixed it, unless you were using an outdated version.

As for the "No such file or directory" error, `hash -p /usr/local/bin/betterdiscordctl betterdiscordctl` would have sufficed.

**Comment by Samega7Cattac** [comment]
I just tried both 1h ago

**Comment by lugia19** [comment]
It just decided to work this time. Didn't change anything myself so it just seems kinda random honestly.

**Comment by orblazer** [comment]
Okey, i have fount the reason. This is because by default is installed with symbol link.

I have run `betterdiscordctl install -c` and now this is perfectly installed.

**Comment by ObserverOfTime** [comment]
Have you somehow sandboxed your home directory and/or `/opt`?

**Comment by orblazer** [comment]
I have just `/home` in other disk

**Comment by ObserverOfTime** [comment]
I don't think that should affect it but I'll take your word for it.
@Samega7Cattac Does using `-c` fix it for you?
