### ISSUE TITLE
BetterDiscordCTL can't find the Discord modules folder.

### ISSUE THREAD

**Issue by Troplo** [bb010g/betterdiscordctl#51]
Discord (Snap) Stats:
Modules in /home/troplo/snap/discord/current/.config/discord/0.0.9/modules
Discord in /snap/discord/current/usr/share/discord
BDCTL cannot find modules even if I specify it.
I run:
betterdiscordctl --snap
Output: ERROR: Discord modules directory not found.

betterdiscordctl install -v -c -d "/snap/discord/current/usr/share/discord" -m "/home/troplo/snap/discord/current/.config/discord/0.09/modules/"
Output: ERROR: Discord modules directory not found.
I'm probably doing something wrong, (running as root. running as the user "troplo" doesn't work either)

**Comment by ObserverOfTime** [comment]
Don't run as root. Have you started Discord at least once before running bdctl?

**Comment by Troplo** [comment]
I have started Discord before running bdctl, and attempted to run at as non-root and it still said that the modules folder isn't found

**Comment by ObserverOfTime** [comment]
Re-download bdctl.
Run `betterdiscordctl install -v -v --snap`.
Post the output if it fails.

**Comment by Troplo** [comment]
huh, running betterdiscordctl install -v -v --snap worked! Not sure why, but it did, Thanks for your help.
