### ISSUE TITLE
Discord update breaks betterdiscord startup

### ISSUE THREAD

**Issue by Murkur** [bb010g/betterdiscordctl#53]
found a issue on regular version of bandage BD that wouldn't allow it to start after the new update and this error carried over to CTL fix is easy as it requires editing a file a elevated user by going to
/home/USERNAME/.local/share/betterdiscordctl/bd/0/betterdiscord
opening the file called index.JS press ctrl F and search for 5000 then change this to 3889 as a new timeout setting and save startup will be slow but will now work
fix by Rhyme at the original BD repository 
https://github.com/rauenzi/BetterDiscordApp/issues/276#issuecomment-553085046

**Comment by ObserverOfTime** [comment]
See #52
