### ISSUE TITLE
Fix to "Something's going on here" bug doesn't seem to be working in my case

### ISSUE THREAD

**Issue by zinec** [bb010g/betterdiscordctl#54]
I'm not sure if it could be distro related, or a new update being shitty with the cl, but betterdiscordcl seems to break discord even if you update to #277. I have even attempted using the old fix, which was to change the 5000 value to 3889, to no avail

**Comment by ObserverOfTime** [comment]
I need more info. What distro? Which Discord? What have you tried?

**Comment by zinec** [comment]
I'm using arch linux and the standard discord install from the repo (the
only one that seems to have this issue). Since I'm not too well versed in
javascript and discord modding i didn't really do much except the two fixes
listed on #53

**Comment by ObserverOfTime** [comment]
You don't need to fix anything manually. Just run `update`.

**Comment by zinec** [comment]
that's the whole reason why i made this post, the update is either not
injecting properly or there's a new update that breaks it

**Comment by ObserverOfTime** [comment]
Do it anyway.

**Comment by zinec** [comment]
just saw the edit, i'll try that out when i get home

**Comment by zinec** [comment]
```
VV: Scanning /opt
VV: Trying flavor ''
V: Using Discord at /opt/discord
V: Found modules in /home/pozu/.config/discord/0.0.9/modules
Updating Git repository...
From https://github.com/rauenzi/BetterDiscordApp
 * branch            injector   -> FETCH_HEAD
HEAD is now at f76eaf5 Merge pull request #277 from MasicoreLord/patch-2
```
There doesn't seem to be anything wrong with the injection so I don't know what is causing this

**Comment by ObserverOfTime** [comment]
Try `betterdiscordctl reinstall -v -v` now.

**Comment by zinec** [comment]
``VV: Scanning /opt
VV: Trying flavor ''
V: Using Discord at /opt/discord
V: Found modules in /home/pozu/.config/discord/0.0.9/modules
Killing Discord processes...
Discord killed (pid 1868467)
Discord killed (pid 1868469)
Discord killed (pid 1868492)
Discord killed (pid 1868529)
V: Removing old injector folder.
V: Linking BetterDiscord injector...
Reinstalled.``
here's the output, didn't do anything of use either

**Comment by ObserverOfTime** [comment]
Open Discord's dev tools with `Ctrl` + `Shift` + `I` and screenshot any errors you see in the console tab.

**Comment by zinec** [comment]
![Screenshot_2019-11-16_09-22-36](https://user-images.githubusercontent.com/46370392/68991097-9b0ecb80-0852-11ea-910d-ccda0fb97630.png)
nothing of interest here, just timezone errors

**Comment by zinec** [comment]
oh my fucking god, discord literally locks you out if you don't have a "standard timezone" set
I'm just gonna close this and scream my lungs out
thanks for the help, but that was a waste of time lmao

**Comment by ObserverOfTime** [comment]
Discord pls.
