### ISSUE TITLE
uninstall doesn't delete all files and directories of BD

### ISSUE THREAD

**Issue by ledudulela** [bb010g/betterdiscordctl#55]
uninstall --flatpak doesn't delete all the files and directories in 
~/.local/share/betterdiscordctl

**Comment by ObserverOfTime** [comment]
It's not supposed to.

**Comment by ledudulela** [comment]
After an update of discord, BetterDiscord options were no longer displayed in Discord.
It's probably due to the change of sub-directories of Discord.
So i changed betterdiscordctl like in issue 45 and executed the commands
<pre>betterdiscordctl uninstall --flatpak</pre>
and to reinstall BD
<pre>betterdiscordctl install --flatpak</pre>
But BetterDiscord options were no longer displayed in Discord.
I deleted all the files and directories in ~/.local/share/betterdiscordctl
and reinstalled BD.
Then BetterDiscord options were displayed in Discord.

Without deletion of this files and directories, betterdiscordctl install only returns:
<pre>
Installed. (Restart Discord if necessary.)
</pre>

With deletion of the files and directories, betterdiscordctl install returns:
<pre>
Cloning https://github.com/rauenzi/BetterDiscordApp...
Clonage dans '/home/myuser/.local/share/betterdiscordctl/bd/0'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 12 (delta 0), reused 7 (delta 0), pack-reused 0
Dépaquetage des objets: 100% (12/12), fait.
Installed. (Restart Discord if necessary.)
</pre>

So if the files already exist in .local/share/betterdiscordctl, there is no cloning during installation 
(and BD does not work in Discord).

**Comment by ObserverOfTime** [comment]
I assume you had installed BD previously and never ran `update`

**Comment by ledudulela** [comment]
exactly

**Comment by ObserverOfTime** [comment]
You were simply supposed to update.

**Comment by ledudulela** [comment]
ok, shame on me
