### ISSUE TITLE
After update BetterDiscord doesn't work

### ISSUE THREAD

**Issue by percheperche** [bb010g/betterdiscordctl#57]
On Manjaro Linux (Arch-based distro). After Discord update BetterDiscord doesn't work. What can I do?

**Comment by ObserverOfTime** [comment]
Duplicate of #53.

**Comment by percheperche** [comment]
Even after doing `betterdiscordctl update` BetterDiscord doesn't work. Here the output of `betterdiscordctl update -v -v`:
VV: Scanning /opt
VV: Trying flavor ''
V: Using Discord at /opt/discord
V: Found modules in /home/perche/.config/discord/0.0.9/modules
Updating Git repository...
Da https://github.com/rauenzi/BetterDiscordApp
 * branch            injector   -> FETCH_HEAD
HEAD ora si trova a f76eaf5 Merge pull request #277 from MasicoreLord/patch-2

**Comment by ObserverOfTime** [comment]
Did you kill discord and restart it?

**Comment by percheperche** [comment]
> Did you kill discord and restart it?

Yes, I killed Discord's process before running the command.

**Comment by ObserverOfTime** [comment]
Open the Discord console with `Ctrl` + `Shift` + `I` and screenshot any errors you see.

**Comment by percheperche** [comment]
> Open the Discord console with `Ctrl` + `Shift` + `I` and screenshot any errors you see.

I've just found these two warnings:
![image](https://user-images.githubusercontent.com/44583807/69569114-43443300-0fbd-11ea-981c-0eba1142366d.png)

**Comment by ObserverOfTime** [comment]
What's the content of `~/.config/BetterDiscord/logs.log`?

**Comment by percheperche** [comment]
```
[INF][20/11/2019, 19:46:31] Hooking dom-ready
[INF][20/11/2019, 19:46:35] Hooked dom-ready
[INF][20/11/2019, 19:46:35] Getting updater
[INF][20/11/2019, 19:46:35] Getting hash from: https://api.github.com/repos/rauenzi/BetterDiscordApp/commits/injector
[INF][20/11/2019, 19:46:36] Getting version from: https://cdn.statically.io/gh/rauenzi/BetterDiscordApp/f76eaf54a9d5c13d9a3c082da3650bb8aec43509/betterdiscord/config.json
[INF][20/11/2019, 19:46:36] Latest Version: 0.3.2
[INF][20/11/2019, 19:46:36] Getting commit hash
[INF][20/11/2019, 19:46:36] Getting hash from: https://api.github.com/repos/rauenzi/BetterDiscordApp/commits/master
[INF][20/11/2019, 19:46:37] cd642701f9e4e2ca6c84ce6a8faaa7970050c1e2
[INF][20/11/2019, 19:46:37] Using hash: cd642701f9e4e2ca6c84ce6a8faaa7970050c1e2
[INF][20/11/2019, 19:46:37] Loading
[INF][20/11/2019, 19:46:42] Loading Resource (//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js)
[INF][20/11/2019, 19:46:42] Loading Resource (//cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/cd642701f9e4e2ca6c84ce6a8faaa7970050c1e2/css/main.min.css)
[INF][20/11/2019, 19:46:43] Loading Resource (//cdn.staticaly.com/gh/rauenzi/BetterDiscordApp/cd642701f9e4e2ca6c84ce6a8faaa7970050c1e2/js/main.min.js)
[INF][20/11/2019, 19:46:43] Starting Up
```

**Comment by ObserverOfTime** [comment]
The log looks outdated. Run `betterdiscordctl reinstall -v -v` and see what happens.

**Comment by percheperche** [comment]
> The log looks outdated. Run `betterdiscordctl reinstall -v -v` and see what happens.

Yep, that did the trick. Thank you very much.
