### ISSUE TITLE
BetterDiscord failing to load

### ISSUE THREAD

**Issue by RaspberryKitty1** [bb010g/betterdiscordctl#58]
I am using Ubuntu
I cant get betterdiscord to load
betterdiscordctl is up to date and installed
i tried reinstalling discord and betterdiscord but it does not load
the logs.log file generated is empty 
I tried both `betterdiscordctl install` and `sudo betterdiscordctl install` and both same results
also tried `betterdiscordctl install -v -c -s /usr/share` and `sudo betterdiscordctl install -v -c -s /usr/share` and same results blank logs.log file
i also tried deleting .config/Betterdiscord

```
Discord: /usr/share/discord
Modules: /home/raspberry/.config/discord/0.0.9/modules
Index modified: yes
Linked injector directory: /home/raspberry/.local/share/betterdiscordctl/bd/0
Linked injector repository: https://github.com/rauenzi/BetterDiscordApp
```

**Comment by ObserverOfTime** [comment]
**Do not use `sudo`.**
Did you run `betterdiscordctl update` after reinstalling?

**Comment by RaspberryKitty1** [comment]
yes

**Comment by RaspberryKitty1** [comment]
thats the only thing i did not think of X3

**Comment by RaspberryKitty1** [comment]
at least i tried some troubleshooting before i made the issue X3

**Comment by ObserverOfTime** [comment]
Using `sudo` is never troubleshooting.

**Comment by RaspberryKitty1** [comment]
no i ment looking at the log file reinstalling discord reinstalling betterdiscord etc...
ik using sudo is not troubleshooting but it what solved the issue last time so i figured ill try it this time whitch did not help this time lol
