### ISSUE TITLE
Add packages list from the readme to the gist

### ISSUE THREAD

**Issue by S-B99** [bb010g/betterdiscordctl#61]
The gist comes up on google first. Only noticed just now there's actual packages for this, would be nice to have them in the gist.

**Comment by ObserverOfTime** [comment]
Including package links is beyond the scope of the gist.

> This Gist contains simple instructions on how to install, update, and uninstall BetterDiscord on Linux.<br/><br/>For more thorough documentation, take a look at betterdiscordctl 's README.

**Comment by S-B99** [comment]
I mean, I've installed this about 3 times now and completely missed that there's a main repo lol. And 

> simple instructions

Including distro packages would be more simple then doing it manually.

**Comment by ObserverOfTime** [comment]
Unlike the manual method, packages are only available on specific distros. Including them in the gist would only make it more complicated.

**Comment by S-B99** [comment]
I don't really understand how including an optional list of package names would make instructions more complicated. It decreases the amount of steps to like 1 instead of 3 to install.

**Comment by ObserverOfTime** [comment]
If `betterdiscordctl` were available in the official repos then it would just be a matter of including the package names, but it's not.

Arch has 1 step (or 4 if no AUR helper is installed), with a dozen variations:
```sh
# git clone https://aur.archlinux.org/<aur helper>
# cd <aur helper>
# makepkg -sic
<aur helper> -S betterdiscordctl-git
```
Ubuntu has 3 steps (or 4 if `software-properties-common` is not installed):
```sh
# sudo apt-get install software-properties-common
sudo add-apt-repository ppa:chronobserver/betterdiscordctl
sudo apt-get update
sudo apt-get install betterdiscordctl
```
Fedora has 2 steps (or 3 if `dnf-plugins-core` is not installed):
```sh
# sudo dnf install dnf-plugins-core
sudo dnf copr enable observeroftime/betterdiscordctl
sudo dnf install betterdiscordctl
```

**Comment by S-B99** [comment]
Oh alright. I didn't realize since it's in the aur and all you have to do is install it. You have a better point.
