### ISSUE TITLE
Does not work on a Chromebook

### ISSUE THREAD

**Issue by Link1147** [bb010g/betterdiscordctl#62]
I followed every step exactly as stated, into the terminal. No issues or errors at all. But, upon opening discord, it looks exactly the same as if i did nothing, please help me here.

I should specify that I am on a Chromebook.

**Comment by ObserverOfTime** [comment]
Chromebooks are not currently supported. If you can get it to work, let us know.

**Comment by Link1147** [comment]
> Chromebooks are not currently supported. If you can get it to work, let us know.

Yes, after a few hours of tinkering, I have been able to get better discord to work. Please note that it is still not 100%. The theme and plugin file buttons within the settings choose to not work sometimes, so using CSS is the only real way to change themes. Also note that the Chromebook that I have is fairly recent, and supports Linux applications to run, as well as supports Android applications to be installed through the app store. If you have any further explanations, I'd be happy to respond.

**Comment by ObserverOfTime** [comment]
> The theme and plugin file buttons within the settings choose to not work sometimes, so using CSS is the only real way to change themes.

That sounds like a [BBD issue](https://github.com/rauenzi/BetterDiscordApp/issues).

**Comment by Link1147** [comment]
> > The theme and plugin file buttons within the settings choose to not work sometimes, so using CSS is the only real way to change themes.
> 
> That sounds like a [BBD issue](https://github.com/rauenzi/BetterDiscordApp/issues).

Yes, I believe it is. Although I haven't found a solution yet. Any ideas?

**Comment by ObserverOfTime** [comment]
Submit a detailed issue there.

**Comment by gregk-git** [comment]
I just installed it on my chromebook, no issues at all, this should be closed, and great app by the way 👍

**Comment by ObserverOfTime** [comment]
You can remove the manual installation and use a [package](https://github.com/bb010g/betterdiscordctl#packages) to let the package manager upgrade it.

**Comment by AnthonyGalli34** [comment]
> I just installed it on my chromebook, no issues with installing, this should be closed, and great app by the way 👍, just one question, how can I get this to auto upgrade every time I boot up?

how to get it on the chromebook?

**Comment by ObserverOfTime** [comment]
[Install Linux.](https://support.google.com/chromebook/answer/9145439?hl=en)
