### ISSUE TITLE
Unable to install BandagedBD on Manjaro Linux

### ISSUE THREAD

**Issue by Syxchemistry** [bb010g/betterdiscordctl#63]
I'm attempting to install bandagedbd, and both the git and normal install from the AUR, give me the same error:
`
sed: can't read /opt/discord/resources/app/index.js: No such file or directory
`

**Comment by ObserverOfTime** [comment]
What's the command you ran?

**Comment by Syxchemistry** [comment]
> What's the command you ran?
No command, it was through the add/remove software program on manjaro. (I added the AUR repo to it for easy access)

**Comment by ObserverOfTime** [comment]
Did you not run `betterdiscordctl`?

**Comment by Syxchemistry** [comment]
> Did you not run `betterdiscordctl`?

I ran that beforehand in console

**Comment by Syxchemistry** [comment]
@ObserverOfTime I just re-ran betterdiscordctl and attempted to install it again, and recieved the same error

**Comment by ObserverOfTime** [comment]
So **how** did you run it?

**Comment by Syxchemistry** [comment]
@ObserverOfTime I ran betterdiscordctl through console, and installed betterdiscord itself from the add/remove software application in manjaro.
![image](https://user-images.githubusercontent.com/60679736/74109814-ae70c080-4b3b-11ea-9045-9a11c5df7589.png)

**Comment by Syxchemistry** [comment]
Also sorry for my stupidity, I'm new to linux as a whole

**Comment by ObserverOfTime** [comment]
**What is the command you used to run `betterdiscordctl`?**

**Comment by Syxchemistry** [comment]
@ObserverOfTime The ones listed on the page
`
$ curl -O https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl

$ chmod +x betterdiscordctl

# mv betterdiscordctl /usr/local/bin
`

**Comment by ObserverOfTime** [comment]
You *still* haven't posted the command I'm asking for but I see that you're using the deprecated version of BD. Just follow the gist instructions precisely and there shouldn't be a problem.

**Comment by Syxchemistry** [comment]
I just reinstalled betterdiscordctl again and it failed. I had to do it like 3 times and it finally loaded. Thanks a lot for your sarcasm
