### ISSUE TITLE
im confused here

### ISSUE THREAD

**Issue by MushroomPixels** [bb010g/betterdiscordctl#64]
$ betterdiscordctl install
ERROR: Discord installation not found. Try specifying it with "--discord".

**Comment by ObserverOfTime** [comment]
How did you install Discord?

**Comment by UltraBlackLinux** [comment]
you have to select your discord: betterdiscordctl install -f discord [discord depends on yours, e.g. canary]

**Comment by ObserverOfTime** [comment]
That's wrong.
```
  -f, --flavors=FLAVORS          Colon-separated list of Discord flavors
                                 (default ':canary:ptb')
```

**Comment by UltraBlackLinux** [comment]
this actually worked for me, if you ment the command is wrong...

**Comment by ObserverOfTime** [comment]
I thought you used `-f discord` which shouldn't work but after you edited your comment I realise that's not the case.

**Comment by keroklown** [comment]
i don't understand, how do you install after it tells you to specify with "--discord"

**Comment by ObserverOfTime** [comment]
> How did you install Discord? What operating system?

**Comment by keroklown** [comment]
ubuntu 20.04 through the software app

**Comment by ObserverOfTime** [comment]
Try `betterdiscordctl install --snap`

**Comment by keroklown** [comment]
thank you, it worked just fine
