### ISSUE TITLE
mkdir: cannot create directory '/run/user/0': Permission denied

### ISSUE THREAD

**Issue by krmkcbs** [bb010g/betterdiscordctl#66]
mkdir: cannot create directory '/run/user/0': Permission denied
mkdir: cannot create directory '/run/user/0': Permission denied
ERROR: Discord modules directory not found.
discord installed from:snap
distro:manjaro linux
command used:sudo betterdiscordctl install --snap
please help

**Comment by ObserverOfTime** [comment]
Don't run it with sudo.
