### ISSUE TITLE
BetterDiscord Does not reload after crash

### ISSUE THREAD

**Issue by SuperWaffleKitty** [bb010g/betterdiscordctl#68]
If discord crashes, better discord will not load upon opening discord. If I reinstall BetterDiscordctl after a crash, it fixes the issue. I am using BetterDiscordctl Canary on Linux.

**Comment by ObserverOfTime** [comment]
Probably not our issue. Submit it [here](https://github.com/rauenzi/BetterDiscordApp/issues).
