### ISSUE TITLE
ERROR: Discord installation not found.

### ISSUE THREAD

**Issue by Trihash** [bb010g/betterdiscordctl#7]
Hello, every command I make (uninstall, install, status) I have this error code: ERROR: Discord installation not found.

**Comment by ObserverOfTime** [comment]
Please provide more information. Where is Discord installed? And what's the full command that you are using?

You can check [examples](https://github.com/bb010g/betterdiscordctl#examples) to see what the proper usage is.

**Comment by KaKi87** [comment]
Hi,

I think we have the same problem :
`betterdiscordctl status -d /usr/share/discord -m ~/.config/discord/0.0.4/modules/`
works, but the "Discord installation not found" error is still there.

Thanks

**Comment by ObserverOfTime** [comment]
That's weird. Can you try `betterdiscordctl install -s /usr/share -v -v` and see if that works? If it does not work, please provide the full output. @KaKi87

**Comment by KaKi87** [comment]
```
tiana@TIANA-PC:~$ betterdiscordctl install -s /usr/share -v -v
VV: Trying flavor ''
VV: Checking /usr/share/discord
VV: Detected /usr/share/discord
V: Using Discord at /usr/share/discord
V: Unpacking core asar...
Updating asar...
/usr/local/bin/betterdiscordctl: ligne 428: npm : commande introuvable
/usr/local/bin/betterdiscordctl: ligne 431: /home/tiana/.local/share/betterdiscordctl/asar/node_modules/asar/bin/asar.js: Aucun fichier ou dossier de ce type
V: Patching core entry...
sed: impossible de lire /home/tiana/.config/discord/0.0.4/modules/discord_desktop_core/core/app/mainScreen.js: Aucun fichier ou dossier de ce type
Cloning https://github.com/rauenzi/BetterDiscordApp...
V: Linking core loader...
ln: impossible de créer le lien symbolique '/home/tiana/.config/discord/0.0.4/modules/discord_desktop_core/core/node_modules/betterdiscord': Aucun fichier ou dossier de ce type
Installed. (Restart Discord if necessary.)
```
![deepin capture-ecran_zone de selection _20180314231855](https://user-images.githubusercontent.com/21284089/37433921-1d09e5ae-27de-11e8-8d63-70c4d47cd62f.png)
Thanks

**Comment by ObserverOfTime** [comment]
Have you installed [nodejs](https://nodejs.org/en/download/package-manager/)?

**Comment by KaKi87** [comment]
I firstly installed nodejs, but it seems the `node` command was not working when I checked it today.
Then I realized that I've forgotten the `npm` package so I installed it, which installed the package `nodejs-legacy`, I don't know what it is but it worked.
Then I updated NodeJS and NPM, I've uninstalled Discord then reinstalled it.
Finally, I ran the install command again, and I have now the following error :
```
VV: Trying flavor ''
VV: Checking /usr/share/discord
VV: Detected /usr/share/discord
V: Using Discord at /usr/share/discord
V: Unpacking core asar...
Updating asar...
/usr/local/bin/betterdiscordctl: ligne 431: /home/tiana/.local/share/betterdiscordctl/asar/node_modules/asar/bin/asar.js: Aucun fichier ou dossier de ce type
V: Patching core entry...
sed: impossible de lire /home/tiana/.config/discord/0.0.4/modules/discord_desktop_core/core/app/mainScreen.js: Aucun fichier ou dossier de ce type
Cloning https://github.com/rauenzi/BetterDiscordApp...
V: Linking core loader...
ln: impossible de créer le lien symbolique '/home/tiana/.config/discord/0.0.4/modules/discord_desktop_core/core/node_modules/betterdiscord': Aucun fichier ou dossier de ce type
Installed. (Restart Discord if necessary.)
```
Thanks.

**Comment by ObserverOfTime** [comment]
Looks like it failed to install `asar` locally.
Install it globally with `sudo npm i -g asar` and then use the `--global-asar` flag. (`betterdiscordctl install -s /usr/share -v -v --global-asar`)

**Comment by bb010g** [comment]
#6's merge should mean that the errors here are more descriptive now.

**Comment by KaKi87** [comment]
@ObserverOfTime It worked ! :)

Could you make betterdiscordctl handle these errors in a future update ?

Thanks !

**Comment by bb010g** [comment]
#6 should have handled that. Closing for now, but if you want to replicate your previous setup, try 1.2.0 with it, see what happens, and post the results here, feel free.

**Comment by KaKi87** [comment]
Hello,

I have betterdiscordctl v1.4.1 and asar is not a problem anymore, but it still doesn't detect automatically Discord in `/usr/share`.

Also it's not relevant to this thread, but it's a fresh Linux setup and Discord was the first program I installed so `git` was not yet. The error appeared in verbose mode, but the script didn't handled it. If you won't, you could at least specify on the readme that the git packet is required.

Thanks !

**Comment by bb010g** [comment]
Git is the first dependency listed in the README.
