### ISSUE TITLE
BetterDiscord not working on canary and update command fails

### ISSUE THREAD

**Issue by MGThePro** [bb010g/betterdiscordctl#70]
So I tried reinstalling BetterDiscordCtl with no luck so far, reinstalled BetterDiscordCtl-git from the AUR, and running betterdiscordctl update just outputs

> WARN: No Git repository found.

Not quite sure what to do anymore

**Comment by ObserverOfTime** [comment]
Run `reinstall` or `install` before `update`.

**Comment by MGThePro** [comment]
Oh, I'm running two instances of Discord (one standard and one canary) and I had to reinstall on the standard first, it's working now! Thanks!
