### ISSUE TITLE
Cannot find module /home/browser-window.js

### ISSUE THREAD

**Issue by BRFNGRNBWS** [bb010g/betterdiscordctl#71]
Hi, after I get this error window after I run betterdiscordctl install and then try to run discord:
https://user-images.githubusercontent.com/11679863/84830265-fd44d000-afdd-11ea-9aee-6021565ad8f6.png

I'm on opensuse tumbleweed. Thanks for any help!

**Comment by ObserverOfTime** [comment]
Run `betterdiscordctl reinstall -v -v` and post the output.
