### ISSUE TITLE
BetterDiscord not working

### ISSUE THREAD

**Issue by Idesmi** [bb010g/betterdiscordctl#72]
Discord recently updated itself to 0.0.10, and BetterDiscord stopped working.

I am using the Stable release of Discord via Flatpak.

This is output of web console after opening the Discord client after BD injection:
![2020-06-26_14-57-21](https://user-images.githubusercontent.com/21034950/85859521-9b465080-b7bd-11ea-970b-48323d529c8e.png)
if it can help.

I have already tried to reinstall both Discord and BD, no fix.

**Comment by ObserverOfTime** [comment]
Run `betterdiscordctl update`.

**Comment by Idesmi** [comment]
This is not fixed? I've run `betterdiscordctl update`, reinstalled, removed and installed, launching Discord every operation.
BetterDiscord still doesn't show up.
