### ISSUE TITLE
"ERROR: Discord modules directory not found." Am I an idiot or what?

### ISSUE THREAD

**Issue by robigan** [bb010g/betterdiscordctl#73]
So recently to protect against AnarachyGrabber I changed the index.js file AnarachyGrabber targeted to be owned by root and cannot be written by my user, now a couple of days ago in my windows installation, BetterDiscord's auto-updater failed, making me use the "injector" to reinstall BetterDiscord, it had been a couple of days since I logged onto my Linux install and when I did today, all it did now was BetterDiscord wasn't booting w/ Discord, I have tried all the fix options, w/ my first command to try out being reinstall. All betterdiscordctl always said was
```
~$ sudo betterdiscordctl reinstall --flatpak
[sudo] password for robigan:         
WARN: Config directory not found for Discord (/var/lib/flatpak/app/com.discordapp.Discord/x86_64/stable/b49ac9277f295fcc565a4ebee2f8e20eda56109d5127634771f8877cf0a286c1/files/discord, /root/.var/app/com.discordapp.Discord/config/discord).
ERROR: Discord modules directory not found.
```
I might be just an idiot but I am truly baffled, note that I have only started using Linux a couple of months ago and I am on flatpak

**Comment by ObserverOfTime** [comment]
Don't use sudo.

**Comment by robigan** [comment]
Yes that is may be true, but 2 things right there, it needs to be able to update that index.js file I mentioned, and it still errored out on me when I ran it without sudo saying it can't remove certain files `Permission denied`

**Comment by ObserverOfTime** [comment]
It can't remove certain files because you ran it with sudo. Delete `~/.local/share/betterdiscordctl`.
