### ISSUE TITLE
[Feature request] Auto-update injector on (re)install

### ISSUE THREAD

**Issue by KaKi87** [bb010g/betterdiscordctl#76]
Hello,

Discord's breaking updates often require the injector to be reinstalled, but they also sometimes require it to be updated.

However, we forget that easily, and report issues for nothing.

So, I'd like to suggest that `betterdiscordctl update` would actually be automatically executed before `betterdiscordctl install` and `betterdiscordctl reinstall`.

Thanks

**Comment by ObserverOfTime** [comment]
> However, we forget that easily, and report issues for nothing.

This could actually be solved by adding an issue template.

**Comment by KaKi87** [comment]
Which will not improve user experience in the way I'd like it to be.

**Comment by ObserverOfTime** [comment]
Forcing an update on (re)install would override any changes made by the user.

**Comment by KaKi87** [comment]
What changes ?

**Comment by ObserverOfTime** [comment]
Any potential changes the user had or wanted to make to the injector.

**Comment by KaKi87** [comment]
I see, but in that case, wouldn't the user fork & PR the installer ?

**Comment by ObserverOfTime** [comment]
I guess they could fork the *injector* and use that fork to update.
