### ISSUE TITLE
Cannot symlink to non-writable location with 0.0.11

### ISSUE THREAD

**Issue by FichteFoll** [bb010g/betterdiscordctl#77]
I use Arch and the AUR packages `betterdiscordctl-git` and `betterdiscord-rauenzi-git`. Until I updated discord to 0.0.11 today, I was able to get up to speed after an update by updating these two packages and then running 
```
$ betterdiscordctl reinstall -b /usr/lib/betterdiscord-rauenzi-git -v -v
```
With 0.0.11, however, I received an error message similar to #75, except my path is `/usr/lib/betterdiscord-rauenzi-git/betterdiscord/config.json` and the file exists but is not user-writable, as it should.

```
~ Σ ll /usr/lib/betterdiscord-rauenzi-git/betterdiscord/config.json
.rw-r--r-- 43 root  9 Aug 20:28 /usr/lib/betterdiscord-rauenzi-git/betterdiscord/config.json
```

Using the `-c` option to copy over the folder instead of symlinking made it work again.

**Comment by ObserverOfTime** [comment]
Since you've installed BBD system-wide you have to use the `-c` flag so it can write to its config file.
You can create a pacman hook to make the file writable on upgrade. Nothing we can do here.
