### ISSUE TITLE
when I try to do step one, it do nothing

### ISSUE THREAD

**Issue by cumontoilet** [bb010g/betterdiscordctl#79]
`curl -O https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl`
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18074  100 18074    0     0  25456      0 --:--:-- --:--:-- --:--:-- 25456
```

and yes, I installed the package by doing` sudo add-apt-repository ppa:chronobserver/betterdiscordctl
`

edit: I am using the linux one

**Comment by ObserverOfTime** [comment]
You've…already installed it. Skip to the BD installation step.
