### ISSUE TITLE
BetterDiscord disappears after Canary updates

### ISSUE THREAD

**Issue by coltondrg** [bb010g/betterdiscordctl#8]
I've got BetterDiscord installed on Discord Canary on Arch Linux. I'm having this problem where every time Discord itself updates, BetterDiscord no longer gets loaded. At first I just suspected that it could be fixed with a simple `betterdiscordctl update` or something like that, but that doesn't work. The only way to get BetterDiscord back is to uninstall it with `betterdiscordctl uninstall`, then reinstall it with `betterdiscordctl install`.

**Comment by ObserverOfTime** [comment]
Yeah, that's normal behaviour. `update` only fetches the most recent BD updates. To reinstall you have to first `uninstall` and then `install` again. 

We might wanna look into adding a `reinstall` command to make this easier @bb010g.

**Comment by coltondrg** [comment]
Okay, so it has to be fully reinstalled after every single Discord update? I have had Discord update 5 times in the same day before (Canary on Linux, perhaps this just comes with the territory), so that's a little frustrating, but if that's how it is, I do believe a reinstall command is necessary.

**Comment by ObserverOfTime** [comment]
It has to be reinstalled whenever Discord changes version or updates internal files. Which Canary does fairly often.

**Comment by ObserverOfTime** [comment]
Implemented in #11.
