### ISSUE TITLE
Not injecting on Discord 0.0.12 deb/Ubuntu 20.04

### ISSUE THREAD

**Issue by ergosteur** [bb010g/betterdiscordctl#80]
I can't get it to work on Discord 0.0.12 deb and Ubuntu 20.04. Discord just starts up normally.
betterdiscordctl shows that it's installed
```$ betterdiscordctl status
Discord: /usr/share/discord
Modules: /home/matt/.config/discord/0.0.12/modules
Index modified: yes
Linked injector directory: /home/matt/.local/share/betterdiscordctl/bd/0
Linked injector repository: https://github.com/rauenzi/BetterDiscordApp
```

**Comment by ObserverOfTime** [comment]
Run `betterdiscordctl update`.

**Comment by ergosteur** [comment]
Just tried that, then did uninstall/reinstall, doesn't seem to have changed.
```$ betterdiscordctl upgrade
betterdiscordctl is already the latest version (1.7.0).
$ betterdiscordctl update
Updating Git repository...
From https://github.com/rauenzi/BetterDiscordApp
 * branch            injector   -> FETCH_HEAD
HEAD is now at 79ff7d8 change backup url
```

**Comment by ObserverOfTime** [comment]
Is there a log file in `~/.config/BetterDiscord`?
Or any `[BetterDiscord]` messages if you launch discord from the terminal?

**Comment by ergosteur** [comment]
Running from Terminal threw a bunch of warnings but seems to work now. Not sure what did it, but thanks for your help and for providing this script!
