### ISSUE TITLE
BandagedDiscord does not launch

### ISSUE THREAD

**Issue by StayBlueee** [bb010g/betterdiscordctl#82]
Linux

![image](https://user-images.githubusercontent.com/23127866/96662030-52814d00-1302-11eb-8913-aeeaea0fa94f.png)

Installed it using the guide provided.

**Comment by ObserverOfTime** [comment]
Run `betterdiscordctl reinstall -v -v` and post the output.

**Comment by Joseph-Cannaday** [comment]
I'm getting the same thing
This is the output after running said cmd:
`VV: Scanning /opt
VV: Trying flavor ''
V: Using Discord at /opt/discord
V: Found modules in /home/doc/.config/discord/0.0.12/modules
Not installed.
`

**Comment by ObserverOfTime** [comment]
So `install` it.

**Comment by Joseph-Cannaday** [comment]
It wouldn't let me because it said the desktop core was missing. Idk if  it has anything to do with the fact that I'm running arch linux, but the AUR download I used was the correct one and I installed discord normally, not through snap.

**Comment by Joseph-Cannaday** [comment]
Update: I finally got it to work after uninstalling both discord and betterdiscord and reinstalling both.

**Comment by bb010g** [comment]
@StayBlueee Can you still reproduce this issue on the latest version?

**Comment by ObserverOfTime** [comment]
There is no injector folder anymore so…
