### ISSUE TITLE
Betterdiscord Partially Works

### ISSUE THREAD

**Issue by d34ddud3** [bb010g/betterdiscordctl#83]
So back in issue #78 I had said the _only_ things that show Betterdiscord is present is the flashing icon in the bottom right and the "public" button below the dm's button in the top left corner. There's also no settings menu for Betterdiscord. Now I've noticed that the emotes seem to work. (I never use emotes so I didn't notice until I typed "Asuna" and there was a little Asuna in there.
![image](https://user-images.githubusercontent.com/70095654/98450921-a368b200-2106-11eb-9d6f-5131ec4ba0c3.png)
(Me discovering Betterdiscord emotes)

So as for when it works and when it doesn't... It really seems like it's just random. Sometimes I start up the computer from a full shutdown and it just works. Sometimes I start up the computer from a full shutdown and it just doesn't. Then when it doesn't I try to run `betterdiscordctl reinstall`, `betterdiscordctl upgrade`, then `betterdiscordctl update` and even then it sometimes works and sometimes doesn't. I'll go ahead and quit Discord completely. (By clicking "Quit Discord" in the system tray) 

Now I'll run each command with `-v -v`.

![image](https://user-images.githubusercontent.com/70095654/98451084-348c5880-2108-11eb-9d3a-80ccdae2a036.png)
![image](https://user-images.githubusercontent.com/70095654/98451112-72897c80-2108-11eb-992b-67ec7ccda2dd.png)
![image](https://user-images.githubusercontent.com/70095654/98451132-a49ade80-2108-11eb-86c4-f5af222265fc.png)

Didn't seem to work this time, but hopefully this provides enough information to really narrow down what the issue might be.

Other potentially useful info's:
OS: Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-12-amd64
For Discord I find this at the bottom of the settings page: 
![image](https://user-images.githubusercontent.com/70095654/98451206-3b679b00-2109-11eb-8de7-ebccc6542dc9.png)

(Edit: Mistakenly said "icon in the bottom left." Fixed to replace "left" with "right."

**Comment by bjotte** [comment]
Hi.
Try this sequence:

1. `betterdiscordctl uninstall`
2. `betterdiscordctl install`
3. `betterdiscordctl update`

This is my recipie for making it work, after many days of trial and error I found the right sequence of commands to use for this. The upgrade option is only for upgrading betterdiscordctl it self, not actually updating betterdiscord.
Also if you have issues with the .deb of discord I would reccommend using the flatpak version as I have never had any issues applying the betterdiscord patches to the flatpak one. just all `--flatpak` to the commands if you try it.

**Comment by d34ddud3** [comment]
@bjotte Yeah that reinstall process has worked, though I've noticed that it seems to work now on `discord-0.0.13.deb`. Though in the Console window on Discord `(Ctrl+Shift+i)` I have found one error and two warnings.

The error:
`[BetterDiscord] [Injector] Getting hash from: https://api.github.com/repos/rauenzi/BetterDiscordApp/commits/gh-pages`
`[Spellchecker] sh is not a valid locale.`

The first warning (This is before the error):
`[CloudSyncUtils] CloudSync is not supported on this platform`

The second warning:
`[NativeDispatchUtils] Tried getting Dispatch instance before instantiated`

I've only powered off my computer a couple times since this Discord update, so the problem might still be there and I've just gotten lucky these past few times. Though I have doubts. And I have noticed that suspending to disk or hibernating causes Betterdiscord to carry over whether it works or not. (Longer winded explanation because I can see how that wording could be hard to understand: By hibernating Bettterdiscord either continues to work or continues not to after turning the computer back on. Which now that I think about it makes perfect sense.)

**Comment by d34ddud3** [comment]
Alright, found a failure. (Basically themes and plugins don't work yet emotes do.)
![image](https://user-images.githubusercontent.com/70095654/101958230-91c46f80-3bc8-11eb-9033-901e0cfe618c.png)
These two new errors popped up with a partially failed Betterdiscord launch. These are the only two new erros/warnings and the others from the previous comment are still there.

**Comment by ObserverOfTime** [comment]
Run `sudo chown d34ddud3 -R /home/d34ddud3/.config/BetterDiscord`.

**Comment by d34ddud3** [comment]
I get that the command is supposed to give my account ownership of the file, but it didn't seem to work. Not even after a reboot. I don't see any typos and the directory seems right. If there's any slight errors in the command I can't point them out. I checked the console in discord (`Ctrl+Shift+i`) and the errors are exactly the same. Maybe Discord is the one that needs permission?

**Comment by ObserverOfTime** [comment]
What's the output of `stat -L -c '%A %U' ~/.config/BetterDiscord/themes/Alice.theme.css`?

**Comment by d34ddud3** [comment]
![image](https://user-images.githubusercontent.com/70095654/102656450-824da500-4139-11eb-843c-018c67041406.png)
Notes:
1. I had to use `sudo` because the first error prompt was "`permission denied`". 
2. Next the command kept complaining that there was no such file or directory unless I was in the `themes` folder. 
3. Before this I was linking the files there from another directory. For the finally working command I had to remove the links and copy the files into the `themes` directory. I also tested it again from the home directory that the terminal begins in and the command worked perfectly fine.

Is it possible that linking the files was the cause of the error in loading them? Furthermore, is it possible that at whatever point in the code that themes load in it stops loading the rest of BD upon load failure? I'm referring to the settings BD adds to the settings menu, as I still do not see that menu.

Summary: The command didn't recognize the linked files as files and so I replaced the links with copies and the command worked. Is it possible that linked files are not recognized by BD as well and that is what prevents the rest of BD from loading?

Conclusion: Linked files might bug out BD.

**Comment by ObserverOfTime** [comment]
Your permissions are probably messed up. Try these commands:
```sh
sudo find -L ~/.config/BetterDiscord -type d -exec chmod -v 755 {} +
sudo find -L ~/.config/BetterDiscord -type f -exec chmod -v 644 {} +
```

**Comment by ObserverOfTime** [comment]
Do you still have errors in the Discord console?

**Comment by d34ddud3** [comment]
Alright... So I decided to run a little test. I ran nine total trials on BD, three for each method of file placement.

1. In the following, "copy" will mean the `Alice.theme.css` file was copied directly into the themes folder, "Link(USB)" will mean that the `Alice.theme.css` file was linked to the themes folder from a USB drive (as I have been doing), and "Link" will mean that `Alice.theme.css` was linked to the themes folder from my `~/Pictures` folder.
2. There are some errors thrown. "sh" will refer to the error `>[Spellchecker] sh is not a valid locale.` PD will stand for, "Permission Denied" which refers to this error: 
![image](https://user-images.githubusercontent.com/70095654/102687487-03964d80-41b5-11eb-9b30-4ebae3bc45c3.png)
"Stat400" will refer to this new error:
![image](https://user-images.githubusercontent.com/70095654/102687730-ab604b00-41b6-11eb-81cf-f7c0b27fa1fa.png)

Now, the results:

Trial    |    File State    |    Error(s)    |    BD Runs (Y/N)


Trial 1:|Copy|sh|Y
Trial 2:|Copy|sh|Y
Trial 3:|Copy|sh|Y
Transition: I removed the file from the themes folder. Then I linked that same file into the themes folder from a USB drive. Before rebooting I checked the Discord console once more. I found not just the `sh` and `PD` errors, but also a new one. 
![image](https://user-images.githubusercontent.com/70095654/102687649-2d9c3f80-41b6-11eb-8faf-ac17fda0751d.png)
Trial 4:|Link(USB)|sh|Y
Trial 5:|Link(USB)|sh , PD , Stat400|N
Trial 6:|Link(USB)|sh , PD|N
Transition: I removed the link to file from the themes folder. Then I linked to it again but from the `~/Pictures` folder in my home directory to the themes folder. This time the PD errors went away, leaving only the sh error. Without having reboot the computer, just like the previous transition, I also checked to see if BD would work and it did. The theme loaded without problems.
Trial 7:|Link|sh|Y
Trial 8:|Link|sh , Stat400|Y
Trial 9:|Link|sh|Y

Additional note: During every run of trials 4-9 I was required to log in to Discord via Gmail/phone# and a password, whereas trials 1-3 did not have this effect.

Conclusion: The root of the problem is linking the file. Having the file, or a copy, in the themes folder will cause the program to run as intended. Having the file linked on the same device will cause the program to require you to log in to Discord, and will otherwise work as intended. Having the file linked from an external drive will cause the program to require you to log in to Discord, and will not entertain themes, plugins, or the BD settings menu.

**Comment by ObserverOfTime** [comment]
The spellcheck error is benign. The 400 error is irrelevant to BD but may be relevant to you having to login.

I've linked a theme from an external drive and everything works so I still can't reproduce your issue.

As a last resort, you can follow these steps:

```sh
betterdiscordctl uninstall
rm -r ~/.config/discord
rm -r ~/.local/share/betterdiscordctl
discord # close it once it's done loading
betterdiscordctl install
discord # may or may not fully work now
```

If any command fails, stop and post the error.

**Comment by d34ddud3** [comment]
![image](https://user-images.githubusercontent.com/70095654/102700633-d083a680-4214-11eb-808f-8b4e79095656.png)

**Comment by ObserverOfTime** [comment]
You can remove it with `rm -rf ~/.local/share/betterdiscordctl`.

**Comment by d34ddud3** [comment]
Alright, apologies for the wait. I've been off the grid for a couple days. I just completed all the steps listed, with the command modification, and did so without an issue. It seems to work for now, but this has often been a farce. I'll comment again after a little while to see if it works.

**Comment by d34ddud3** [comment]
Alright, it works. Confirmed. Thank you very much @ObserverOfTime
