### ISSUE TITLE
cant clone https://github.com/rauenzi/BetterDiscordApp on ubuntu 20.04.1

### ISSUE THREAD

**Issue by shafiahaz2478** [bb010g/betterdiscordctl#85]
HI 
I cant install betterdiscord when i execute betterdiscordctl install 
i am getting 
![image](https://user-images.githubusercontent.com/69790524/99895653-9caf7280-2ca2-11eb-86bd-bf78ee49ac3b.png)
any fix

**Comment by ObserverOfTime** [comment]
There might be something wrong with your gitconfig. That trailing slash shouldn't be there.
Try running `betterdiscordctl install -r https://github.com/rauenzi/BetterDiscordApp`.

**Comment by shafiahaz2478** [comment]
ok I will try

**Comment by shafiahaz2478** [comment]
and I checked code what is making the cause of that slash I couldn't find it

**Comment by shafiahaz2478** [comment]
when i remove line:480 
![image](https://user-images.githubusercontent.com/69790524/99908354-a913e980-2cfb-11eb-81dc-b296cbfa7ced.png) 
and download this source code  and running this again it works
when i launch discord i get this
![image](https://user-images.githubusercontent.com/69790524/99908389-d8c2f180-2cfb-11eb-9b8b-ef5ed680dd19.png)
I dont know its nodejs problem

**Comment by ObserverOfTime** [comment]
Please don't remove lines...

**Comment by shafiahaz2478** [comment]
well I did then undo it

**Comment by ObserverOfTime** [comment]
As far as I can tell, this is not our issue. Google is your friend.
