### ISSUE TITLE
Not working for me; on Kali Linux

### ISSUE THREAD

**Issue by ConnorAhern** [bb010g/betterdiscordctl#86]
Errors in console: (censored text is my user account name)

![image](https://user-images.githubusercontent.com/61570792/99910793-e6995800-2ca4-11eb-9aff-67589d27fa43.png)

I have tried all the fixes on the issues in this repository, none have worked.

**Comment by Inotamira** [comment]
Same here, it kind of looks like Discords updated to cut off betterdiscord.

**Comment by Inotamira** [comment]
> Errors in console: (censored text is my user account name)
> 
> ![image](https://user-images.githubusercontent.com/61570792/99910793-e6995800-2ca4-11eb-9aff-67589d27fa43.png)
> 
> I have tried all the fixes on the issues in this repository, none have worked.

Are you perchance using the electron build of Discord?

**Comment by octoshrimpy** [comment]
Had same error on Arch, using electron. this fixed it: 
https://github.com/bb010g/betterdiscordctl/issues/83#issuecomment-723498118
@SwxtchCode @Inotamira

**Comment by SwxtchCode** [comment]
I tried that. It also did not work.

**Comment by ObserverOfTime** [comment]
Are those the only errors in the console? Check `~/.config/BetterDiscord` & `~/.config/BetterDiscord/plugins` for any invalid json files.

**Comment by JonasBBX** [comment]
Dont know if this is going to help but maybe remove uninstall betterdiscordctl and install it again and doing the mv command go into root account with sudo -s dont use sudo if you did last time

**Comment by bb010g** [comment]
@ConnorAhern Can you still reproduce this issue on the latest version?

**Comment by ConnorAhern** [comment]
Currently, I don't have my Linux machine. Sorry.
