### ISSUE TITLE
Linked injector directory: no

### ISSUE THREAD

**Issue by ALtaDoodler** [bb010g/betterdiscordctl#92]
havin trouble getting bd to install. i got it before, but don't remember what i did to fix it (i think i changed a file location, but i don't know if it was in the code or what). here's a pic that shows everything hopefully.
![Screenshot from 2021-01-13 12-28-15](https://user-images.githubusercontent.com/64117835/104496186-4540cb00-559e-11eb-80c8-69a559080cff.png)
i also looked at the directories in the error message, and for the bottom 2, all i got was usr/local/bin/betterdiscordctl (the only file there) and home/.local/share/betterdiscordctl/bd_map (also the only file there)
i used snap to install discord, and was trying --snap in the terminal, but that on its own gets a modules not found error. i'm using zorin 15.3, and it's a fresh install. any help would be great, cuz i like usin this thing.

**Comment by ObserverOfTime** [comment]
**DO NOT USE SUDO**

**Comment by ALtaDoodler** [comment]
ok, but then this shows up
![Screenshot from 2021-01-14 10-46-48](https://user-images.githubusercontent.com/64117835/104621569-dfb01580-5655-11eb-8e5b-4ac4629949f0.png)

**Comment by ALtaDoodler** [comment]
never mind, i got it.
