### ISSUE TITLE
Discord Canary now thinks im in the Discord website.

### ISSUE THREAD

**Issue by ErKaf** [bb010g/betterdiscordctl#94]
![image](https://user-images.githubusercontent.com/60077292/107861638-78010c00-6e47-11eb-95f6-75ce5e392ea6.png)

**Comment by ObserverOfTime** [comment]
BBD doesn't work on Canary anymore. See https://github.com/rauenzi/BetterDiscordApp/issues/442#issuecomment-768131571.
