### ISSUE TITLE
BetterDiscord incompatible with Discord's new security measures (BD does not load)

### ISSUE THREAD

**Issue by l1ving** [bb010g/betterdiscordctl#96]
Unsure how to troubleshoot, sorry.

```
mika % betterdiscordctl status
Discord: /opt/discord-canary
Modules: /home/mika/.config/discordcanary/0.0.119/modules
Index modified: yes
Linked injector directory: /home/mika/.local/share/betterdiscordctl/bd/0
Linked injector repository: https://github.com/rauenzi/BetterDiscordApp
mika % betterdiscordctl reinstall -f canary
Killing Discord canary processes...
discord-canary killed (pid 397977)
DiscordCanary killed (pid 397978)
DiscordCanary killed (pid 397981)
DiscordCanary killed (pid 397982)
DiscordCanary killed (pid 397984)
DiscordCanary killed (pid 398012)
DiscordCanary killed (pid 398020)
DiscordCanary killed (pid 398058)
DiscordCanary killed (pid 398071)
DiscordCanary killed (pid 398156)
Reinstalled.
mika % betterdiscordctl status
Discord: /opt/discord-canary
Modules: /home/mika/.config/discordcanary/0.0.119/modules
Index modified: yes
Linked injector directory: /home/mika/.local/share/betterdiscordctl/bd/0
Linked injector repository: https://github.com/rauenzi/BetterDiscordApp
mika % betterdiscordctl status^C
mika % betterdiscordctl -v status
V: Using Discord at /opt/discord-canary
V: Found modules in /home/mika/.config/discordcanary/0.0.119/modules
Discord: /opt/discord-canary
Modules: /home/mika/.config/discordcanary/0.0.119/modules
Index modified: yes
Linked injector directory: /home/mika/.local/share/betterdiscordctl/bd/0
Linked injector repository: https://github.com/rauenzi/BetterDiscordApp
mika % betterdiscordctl install -f canary
ERROR: Already installed.
```

```
mika % discord-canary &
[1] 398206
mika % DiscordCanary 0.0.119
(node:398207) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

(DiscordCanary:398207): Gtk-WARNING **: 11:23:48.926: Failed to parse /home/mika/.config/gtk-3.0/settings.ini: Key file does not have group “Settings”
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/mika/.config/discordcanary/0.0.119/modules
[Modules] Module installed file path: /home/mika/.config/discordcanary/0.0.119/modules/installed.json
[Modules] Module download path: /home/mika/.config/discordcanary/0.0.119/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discord.com/api/modules/canary/versions.json
[Modules] No module updates available.

```

![image](https://user-images.githubusercontent.com/17222512/109680179-4330cc80-7b4a-11eb-86b0-d449df5f9517.png)

---

If there's other information I can provide that would help I can provide that, not sure what do to from here.

**Comment by l1ving** [comment]
Works after uninstalling canary and installing stable. Would be willing to troubleshoot why canary won't work.

**Comment by ObserverOfTime** [comment]
BBD doesn't work on Canary anymore. See https://github.com/rauenzi/BetterDiscordApp/issues/442#issuecomment-768131571.

**Comment by True-cc** [comment]
https://github.com/rauenzi/BetterDiscordApp/issues/598#issuecomment-806070645 seemed to fix it for me.

**Comment by l1ving** [comment]
> [rauenzi/BetterDiscordApp#598 (comment)](https://github.com/rauenzi/BetterDiscordApp/issues/598#issuecomment-806070645) seemed to fix it for me.

That looks like it adds a lot of unnecessary code and has base64 encoded html inside and a bunch of other stuff for some reason?? I really wouldn't trust some random mediafire link

**Comment by ObserverOfTime** [comment]
@therealOri This issue was pinned 3 weeks ago. That was when the update that broke BD was introduced in canary. The same update landed in stable yesterday or today. Follow the link in my earlier comment for more info and stop expecting me to spoonfeed you.

**Comment by therealOri** [comment]
@ObserverOfTime 
I don't expect to be spoonfed information.
and thanks for clarification on when it was pinned, It only showed up for me after my issue was closed.

I just expect to have at least a link that redirects me or anyone to the "duplicate" issue when you closed my main issue so I could look into it further myself. Instead of sifting through 80+ closed issues to find the not so duplicated "duplicate" issue.

It's not even that hard to do either, literally just copy the link and paste it with a reason for closing the issue.
`Closed for being a duplicate: <link of OG issue here>.`
that simple and saves everyone else time. AND they get an answer.

instead of `"closed" and added some labels.`

(i'd respond to you on my closed issue but that is not where you pinged me.)

**Comment by ObserverOfTime** [comment]
@therealOri I had to close half a dozen duplicates so I stopped responding after the first two.
It's not even that hard to just read the pinned issues before submitting a new one.

**Comment by bb010g** [comment]
I'm going to reopen this until we either officially deprecate betterdiscordctl or make it compatible with the new installation method.

**Comment by bb010g** [comment]
Working with the new BetterDiscord installation is very doable.

**Comment by True-cc** [comment]
That's good. I hope to get a good betterdiscord again!

**Comment by ObserverOfTime** [comment]
You can use the GUI [installer](https://github.com/BetterDiscord/Installer/releases/download/v1.0.0-beta/BetterDiscord-Linux.AppImage) in the meantime.

**Comment by SuwakoMmh** [comment]
> I'm going to reopen this until we either officially deprecate betterdiscordctl or make it compatible with the new installation method.

I Hope betterdiscordctl won't get deprecated, I honestly love the CLI tool, the AppImage is fat for not much and can't be scripted.
Thanks for betterdiscordctl !

**Comment by IvarWithoutBones** [comment]
I'd really love for betterdiscordctl not to get deprecated as well, having an easy and minimal CLI alternative to the GUI application would be great.

**Comment by Dead1Memories2** [comment]
> You can use the GUI [installer](https://github.com/BetterDiscord/Installer/releases/download/v1.0.0-beta/BetterDiscord-Linux.AppImage) in the meantime. It does not support flatpak and snap though.
THANK YOU, I tried installing BD from terminal but never worked, i'm kinda new to these linux things... Thank you for giving the GUI installer.

**Comment by Dead1Memories2** [comment]
> You can use the GUI [installer](https://github.com/BetterDiscord/Installer/releases/download/v1.0.0-beta/BetterDiscord-Linux.AppImage) in the meantime. It does not support flatpak and snap though.

Thank you so much.

**Comment by bb010g** [comment]
Sorry for all the delay. betterdiscordctl v2.0.0 is in final review, and should be released within the next couple days. Early tests of #120 from anyone running Snap or Flatpak would be appreciated.

**Comment by mkikets99** [comment]
No luck for me to install on Flatpak

Flatpak 1.10.2
Discord: Stable 85712 (10a9883)
Linux 64-Bit (Fedora v33)
![image](https://user-images.githubusercontent.com/22869811/119242747-362fe200-bb69-11eb-8bae-ea187d7dc745.png)
![image](https://user-images.githubusercontent.com/22869811/119242749-447dfe00-bb69-11eb-9ee7-9c398623b618.png)
(Sorry for Cyrillic)
```
Discord 0.0.14
(node:5) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Gtk-Message: 01:47:52.909: Failed to load module "xapp-gtk3-module"
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/mkikets/.var/app/com.discordapp.Discord/config/discord/0.0.14/modules
[Modules] Module installed file path: /home/mkikets/.var/app/com.discordapp.Discord/config/discord/0.0.14/modules/installed.json
[Modules] Module download path: /home/mkikets/.var/app/com.discordapp.Discord/config/discord/0.0.14/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
[Modules] No module updates available.
```

And... Discord act like a browser app...

**Comment by bb010g** [comment]
@mkikets99 Did you use `betterdiscordctl` v2.0.0? (`betterdiscordctl --version` will tell you.)

Try running `cd ~/Downloads`, `curl -LO "https://github.com/bb010g/betterdiscordctl/raw/beta/betterdiscordctl"`, and then `chmod +x ./betterdiscordctl`. `./betterdiscordctl --version` (*not* `betterdiscordctl --version`; you want to use the version in your user's `Downloads` directory) should print `betterdiscordctl 2.0.0`. Try using `./betterdiscordctl` with your Flatpak install.

If you still have problems, please provide the commands you ran (and their outputs) and the outputs of `./betterdiscordctl --version` & `./betterdiscordctl status`.

**Comment by mkikets99** [comment]
> @mkikets99 Did you use `betterdiscordctl` v2.0.0? (`betterdiscordctl --version` will tell you.)
> 
> Try running `cd ~/Downloads`, `curl -LO "https://github.com/bb010g/betterdiscordctl/raw/beta/betterdiscordctl"`, and then `chmod +x ./betterdiscordctl`. `./betterdiscordctl --version` (_not_ `betterdiscordctl --version`; you want to use the version in your user's `Downloads` directory) should print `betterdiscordctl 2.0.0`. Try using `./betterdiscordctl` with your Flatpak install.
> 
> If you still have problems, please provide the commands you ran (and their outputs) and the outputs of `./betterdiscordctl --version` & `./betterdiscordctl status`.

Ok, so is is posible to install on standard version...
But... Did something changed in 2.0.0? I mean...
```
[mkikets@localhost ~]$ betterdiscordctl install --flatpak
ERROR: Unknown top-level option: --flatpak
Use `betterdiscordctl --help` for more information.
.......
[mkikets@localhost ~]$ betterdiscordctl install --d-install flatpak
ERROR: Unknown top-level option: --d-install
Use `betterdiscordctl --help` for more information.
.......
[mkikets@localhost ~]$ betterdiscordctl install -i flatpak
ERROR: Unknown top-level option: -i
Use `betterdiscordctl --help` for more information.
```
Did I missing something?

**Comment by bb010g** [comment]
@mkikets99 You need to use `./betterdiscordctl --flatpak install`, as `--flatpak` is a top-level option. The first error should have said `ERROR: Unknown |install| option: --flatpak`, which I'll fix.

**Comment by mkikets99** [comment]
> @mkikets99 You need to use `./betterdiscordctl --flatpak install`, as `--flatpak` is a top-level option. The first error should have said `ERROR: Unknown |install| option: --flatpak`, which I'll fix.

Well seems like something isn't working...
```
[mkikets@localhost ~]$ betterdiscordctl --version
betterdiscordctl 2.0.0
[mkikets@localhost ~]$ betterdiscordctl --flatpak install
ERROR: Unknown top-level option: --flatpak
Use `betterdiscordctl --help` for more information.

```

**Comment by ObserverOfTime** [comment]
It's `betterdiscordctl -i flatpak install` now. Don't ask why.

**Comment by bb010g** [comment]
Oh yeah, sorry. Forgot we changed the syntax for that.

**Comment by bb010g** [comment]
betterdiscordctl v2.0.0 has been released! https://github.com/bb010g/betterdiscordctl/releases/v2.0.0 provides a changelog that goes over the CLI refresh. If you have problems with the new release, reporting them in new issues would be preferred so that everyone subscribed to this issue isn't notified.
