### ISSUE TITLE
betterdiscordctl upgrade issue zsh

### ISSUE THREAD

**Issue by Xenfo** [bb010g/betterdiscordctl#97]
Downloading betterdiscordctl...
Successfully updated betterdiscordctl.
/usr/local/bin/betterdiscordctl: line 662: syntax error near unexpected token `)'

**Comment by ObserverOfTime** [comment]
Use bash.

**Comment by ObserverOfTime** [comment]
Actually it does seem to be an issue in bash too.

**Comment by ObserverOfTime** [comment]
It looks like the command succeeds anyway and I can't reproduce it on v1.7.1 so I'm closing this again.
