### ISSUE TITLE
Not working on kali linux-Discord thinks it is a browser when betterdiscord is installed

### ISSUE THREAD

**Issue by GingerCam** [bb010g/betterdiscordctl#98]
Discord thinks that it is a browser so it is not letting me use betterdiscord or voice input or screen sharing.
I have tried uninstalling and purging discords config files, but it doesn't work
it worked fine yesterday, until an update this morning
![image](https://user-images.githubusercontent.com/61910379/112282720-4289e280-8c7f-11eb-80b5-f7b57b020d9f.png)

**Comment by Melechtna** [comment]
Having the exact same issue on OpenSUSE and an Arch based system I was using earlier.

**Comment by ObserverOfTime** [comment]
See https://github.com/bb010g/betterdiscordctl/issues/96#issuecomment-789172977. Discord seems to be rolling out the changes to stable for some people.

**Comment by GingerCam** [comment]
> See [#96 (comment)](https://github.com/bb010g/betterdiscordctl/issues/96#issuecomment-789172977). Discord seems to be rolling out the changes to stable for some people.

is there any way to fix it?

**Comment by ObserverOfTime** [comment]
None that I know of.

**Comment by GingerCam** [comment]
> None that I know of.

ok thanks for trying

**Comment by EmeraldSnorlax** [comment]
Just want to chime in and say that after upgrading Discord on Arch Linux (5.11.8-arch1-1), Discord stable 80314 (649cbaf) Linux 64-Bit, that I am having all the symptoms described -- Discord is showing the banner as pictured below:

![d](https://user-images.githubusercontent.com/43452521/112302859-77079980-8c93-11eb-9695-6b4036e5b4fc.png)

betterdiscordctl also fails to inject, as described in #96, even though I'm on stable
